// 35-o'yin: masalalar banki. Har masala qo'lda yozilgan (QOIDALAR §4.3 istisnosi).
// Har biri: shart, kirish/chiqish formati, ko'rinadigan namuna, yashirin testlar, namunali yechim va maslahat.
// tests/bank.test.js har bir yechimni barcha testlarda ishga tushirib tekshiradi.
(function (root) {
  "use strict";

  const OSON = [
    {
      id: "yigindi",
      title: "Ikki son yigʻindisi",
      what: "Ikkita butun son berilgan. Ularning yigʻindisini chiqar.",
      kirish: "Ikki satrda ikkita butun son.",
      chiqish: "Bitta son — yigʻindi.",
      namuna: { stdin: ["12", "30"], out: ["42"] },
      tests: [["5", "7"], ["0", "0"], ["-3", "10"], ["100", "250"]],
      solution: "a = int(input())\nb = int(input())\nprint(a + b)",
      hint: "Ikkita input() kerak, keyin qoʻshasan.",
    },
    {
      id: "kvadrat",
      title: "Kvadrat",
      what: "Bitta son berilgan. Uning kvadratini chiqar.",
      kirish: "Bitta butun son.",
      chiqish: "Bitta son — kvadrati.",
      namuna: { stdin: ["7"], out: ["49"] },
      tests: [["3"], ["0"], ["-4"], ["25"]],
      solution: "n = int(input())\nprint(n * n)",
      hint: "n * n yoki n ** 2.",
    },
    {
      id: "juft-toq",
      title: "Juft yoki toq",
      what: 'Bitta son berilgan. Agar u juft boʻlsa "juft", aks holda "toq" deb yoz.',
      kirish: "Bitta butun son.",
      chiqish: "juft yoki toq.",
      namuna: { stdin: ["10"], out: ["juft"] },
      tests: [["7"], ["0"], ["100"], ["13"]],
      solution: 'n = int(input())\nif n % 2 == 0:\n    print("juft")\nelse:\n    print("toq")',
      hint: "Juftlikni % 2 bilan tekshiriladi: qoldiq 0 boʻlsa — juft.",
    },
    {
      id: "eng-katta-3",
      title: "Uchtadan kattasi",
      what: "Uchta son berilgan. Eng kattasini chiqar.",
      kirish: "Uch satrda uchta butun son.",
      chiqish: "Bitta son — eng kattasi.",
      namuna: { stdin: ["3", "9", "5"], out: ["9"] },
      tests: [["10", "2", "7"], ["1", "1", "1"], ["-5", "-2", "-9"], ["4", "4", "8"]],
      solution: "a = int(input())\nb = int(input())\nc = int(input())\nbest = a\nif b > best:\n    best = b\nif c > best:\n    best = c\nprint(best)",
      hint: "Birinchisini eng katta deb ol, keyin qolganlari bilan solishtir.",
    },
    {
      id: "yigindi-n",
      title: "Birdan n gacha",
      what: "Bitta musbat son berilgan. 1 dan shu songacha (uning oʻzi ham kiradi) sonlar yigʻindisini chiqar.",
      kirish: "Bitta musbat butun son.",
      chiqish: "Bitta son — yigʻindi.",
      namuna: { stdin: ["5"], out: ["15"] },
      tests: [["1"], ["10"], ["100"], ["3"]],
      solution: "n = int(input())\ns = 0\nfor i in range(1, n + 1):\n    s += i\nprint(s)",
      hint: "range(1, n + 1) — n ning oʻzi ham kirishi uchun.",
    },
    {
      id: "oraliq-yigindi",
      title: "a dan b gacha",
      what: "Ikkita son berilgan: a va b (a ≤ b). a dan b gacha (ikkalasi ham kiradi) sonlar yigʻindisini chiqar.",
      kirish: "Ikki satrda a va b.",
      chiqish: "Bitta son — yigʻindi.",
      namuna: { stdin: ["3", "6"], out: ["18"] },
      tests: [["1", "5"], ["7", "7"], ["0", "10"], ["10", "20"]],
      solution: "a = int(input())\nb = int(input())\ns = 0\nfor i in range(a, b + 1):\n    s += i\nprint(s)",
      hint: "a dan boshlab b + 1 gacha yur.",
    },
    {
      id: "musbat-manfiy",
      title: "Musbat, manfiy yoki nol",
      what: 'Bitta son berilgan. "musbat", "manfiy" yoki "nol" deb yoz.',
      kirish: "Bitta butun son.",
      chiqish: "musbat, manfiy yoki nol.",
      namuna: { stdin: ["-7"], out: ["manfiy"] },
      tests: [["5"], ["0"], ["-1"], ["1000"]],
      solution: 'n = int(input())\nif n > 0:\n    print("musbat")\nelif n < 0:\n    print("manfiy")\nelse:\n    print("nol")',
      hint: "Uch holat — if, elif va else.",
    },
    {
      id: "yulduzcha",
      title: "Yulduzchalar",
      what: "Bitta musbat son berilgan. Shuncha satr chiqar: birinchi satrda 1 ta yulduzcha, ikkinchisida 2 ta va hokazo.",
      kirish: "Bitta musbat butun son.",
      chiqish: "n ta satr.",
      namuna: { stdin: ["3"], out: ["*", "**", "***"] },
      tests: [["1"], ["5"], ["2"], ["7"]],
      solution: 'n = int(input())\nfor i in range(1, n + 1):\n    print("*" * i)',
      hint: '"*" * i — yulduzchani i marta takrorlaydi.',
    },
  ];

  const ORTA = [
    {
      id: "raqamlar-yigindisi",
      title: "Raqamlar yigʻindisi",
      what: "Bitta musbat son berilgan. Uning raqamlari yigʻindisini chiqar.",
      kirish: "Bitta musbat butun son.",
      chiqish: "Bitta son.",
      namuna: { stdin: ["5382"], out: ["18"] },
      tests: [["7"], ["100"], ["999"], ["10203"]],
      solution: "n = int(input())\ns = 0\nwhile n > 0:\n    s += n % 10\n    n = n // 10\nprint(s)",
      hint: "n % 10 — oxirgi raqam, n // 10 — qolgani.",
    },
    {
      id: "teskari-son",
      title: "Teskari son",
      what: "Bitta musbat son berilgan. Uni teskari oʻgirib chiqar.",
      kirish: "Bitta musbat butun son.",
      chiqish: "Bitta son.",
      namuna: { stdin: ["1234"], out: ["4321"] },
      tests: [["7"], ["100"], ["9081"], ["10"]],
      solution: "n = int(input())\nt = 0\nwhile n > 0:\n    t = t * 10 + n % 10\n    n = n // 10\nprint(t)",
      hint: "Har qadamda: t = t * 10 + oxirgi raqam.",
    },
    {
      id: "farq",
      title: "Eng katta va eng kichik farqi",
      what: "Bitta satrda bir nechta son berilgan. Eng katta va eng kichik sonning farqini chiqar.",
      kirish: "Bitta satrda boʻsh joy bilan ajratilgan sonlar.",
      chiqish: "Bitta son.",
      namuna: { stdin: ["3 9 5"], out: ["6"] },
      tests: [["7"], ["10 2 8 4"], ["5 5 5"], ["-3 10 0"]],
      solution: "a = input().split()\nbest = int(a[0])\nworst = int(a[0])\nfor x in a:\n    v = int(x)\n    if v > best:\n        best = v\n    if v < worst:\n        worst = v\nprint(best - worst)",
      hint: "Ikkita quti kerak: eng katta va eng kichik.",
    },
    {
      id: "juftlar-soni",
      title: "Nechta juft",
      what: "Bitta satrda bir nechta son berilgan. Nechtasi juft ekanini chiqar.",
      kirish: "Bitta satrda boʻsh joy bilan ajratilgan sonlar.",
      chiqish: "Bitta son.",
      namuna: { stdin: ["1 2 3 4"], out: ["2"] },
      tests: [["7"], ["2 4 6"], ["1 3 5"], ["0 1 2 3 4 5"]],
      solution: "a = input().split()\nsoni = 0\nfor x in a:\n    if int(x) % 2 == 0:\n        soni += 1\nprint(soni)",
      hint: "split() dan keyin har boʻlakni int() bilan songa oʻgir.",
    },
    {
      id: "unlilar",
      title: "Unli harflar",
      what: "Bitta soʻz berilgan. Undagi unli harflar (a, e, i, o, u) sonini chiqar.",
      kirish: "Bitta soʻz (kichik harflar bilan).",
      chiqish: "Bitta son.",
      namuna: { stdin: ["qabila"], out: ["3"] },
      tests: [["python"], ["aeiou"], ["kkk"], ["dastur"]],
      solution: 'soz = input()\nsoni = 0\nfor harf in soz:\n    if harf in "aeiou":\n        soni += 1\nprint(soni)',
      hint: 'harf in "aeiou" — harf unlilar orasida bormi.',
    },
    {
      id: "boluvchilar-soni",
      title: "Boʻluvchilar soni",
      what: "Bitta musbat son berilgan. Uning nechta boʻluvchisi borligini chiqar.",
      kirish: "Bitta musbat butun son.",
      chiqish: "Bitta son.",
      namuna: { stdin: ["12"], out: ["6"] },
      tests: [["1"], ["7"], ["36"], ["100"]],
      solution: "n = int(input())\nsoni = 0\nfor i in range(1, n + 1):\n    if n % i == 0:\n        soni += 1\nprint(soni)",
      hint: "1 dan n gacha yurib, qoldiq nolga tengini sana.",
    },
    {
      id: "fibonachchi",
      title: "Fibonachchi",
      what: "Bitta son n berilgan. Fibonachchi ketma-ketligining n-hadini chiqar. Ketma-ketlik: 0, 1, 1, 2, 3, 5, … (1-had — 0).",
      kirish: "Bitta musbat butun son n.",
      chiqish: "Bitta son.",
      namuna: { stdin: ["7"], out: ["8"] },
      tests: [["1"], ["2"], ["10"], ["20"]],
      solution: "n = int(input())\na = 0\nb = 1\nfor i in range(n - 1):\n    a, b = b, a + b\nprint(a)",
      hint: "Ikki qutini almashtirib bor: a, b = b, a + b.",
    },
    {
      id: "palindrom",
      title: "Palindrom",
      what: 'Bitta soʻz berilgan. Agar u teskari oʻqilganda ham bir xil boʻlsa "ha", aks holda "yoʻq" deb yoz.',
      kirish: "Bitta soʻz.",
      chiqish: "ha yoki yoʻq.",
      namuna: { stdin: ["abba"], out: ["ha"] },
      tests: [["qabila"], ["a"], ["aba"], ["python"]],
      solution: 'soz = input()\nt = ""\nfor harf in soz:\n    t = harf + t\nif t == soz:\n    print("ha")\nelse:\n    print("yoʻq")',
      hint: "Avval soʻzni teskari yasab ol, keyin solishtir.",
    },
  ];

  const QIYIN = [
    {
      id: "tubmi",
      title: "Tub sonmi",
      what: 'Bitta son berilgan. Agar u tub son boʻlsa "ha", aks holda "yoʻq" deb yoz. (Tub son — 1 va oʻzidan boshqa boʻluvchisi yoʻq, 1 dan katta son.)',
      kirish: "Bitta butun son.",
      chiqish: "ha yoki yoʻq.",
      namuna: { stdin: ["13"], out: ["ha"] },
      tests: [["1"], ["2"], ["9"], ["97"], ["100"]],
      solution: 'n = int(input())\ntub = True\nif n < 2:\n    tub = False\nd = 2\nwhile d * d <= n:\n    if n % d == 0:\n        tub = False\n    d += 1\nif tub:\n    print("ha")\nelse:\n    print("yoʻq")',
      hint: "Boʻluvchini d * d <= n gacha qidirsang yetadi. 1 va 0 tub emas.",
    },
    {
      id: "tublar-soni",
      title: "Nechta tub son",
      what: "Bitta musbat son n berilgan. 2 dan n gacha (n ham kiradi) nechta tub son borligini chiqar.",
      kirish: "Bitta musbat butun son.",
      chiqish: "Bitta son.",
      namuna: { stdin: ["10"], out: ["4"] },
      tests: [["1"], ["2"], ["20"], ["50"]],
      solution: "n = int(input())\nsoni = 0\nfor x in range(2, n + 1):\n    tub = True\n    d = 2\n    while d * d <= x:\n        if x % d == 0:\n            tub = False\n        d += 1\n    if tub:\n        soni += 1\nprint(soni)",
      hint: "Har bir sonni alohida tekshir — ichma-ich sikl kerak boʻladi.",
    },
    {
      id: "ekub",
      title: "Eng katta umumiy boʻluvchi",
      what: "Ikkita musbat son berilgan. Ularning eng katta umumiy boʻluvchisini chiqar.",
      kirish: "Ikki satrda ikkita musbat son.",
      chiqish: "Bitta son.",
      namuna: { stdin: ["12", "18"], out: ["6"] },
      tests: [["7", "13"], ["100", "75"], ["5", "5"], ["36", "12"]],
      solution: "a = int(input())\nb = int(input())\nwhile b > 0:\n    r = a % b\n    a = b\n    b = r\nprint(a)",
      hint: "Evklid usuli: kattasini kichigiga boʻlib, qoldiq bilan davom et.",
    },
    {
      id: "ikkinchi-katta",
      title: "Ikkinchi eng katta",
      what: "Bitta satrda bir nechta har xil son berilgan. Ikkinchi eng kattasini chiqar.",
      kirish: "Bitta satrda kamida ikkita har xil son.",
      chiqish: "Bitta son.",
      namuna: { stdin: ["3 9 5"], out: ["5"] },
      tests: [["10 2"], ["1 7 4 9 2"], ["100 50 75"], ["-3 -1 -7"]],
      solution: "a = input().split()\nb = []\nfor x in a:\n    b.append(int(x))\nb = sorted(b)\nprint(b[len(b) - 2])",
      hint: "Saralangan roʻyxatda oxiridan ikkinchisi kerak.",
    },
    {
      id: "ikkilik",
      title: "Ikkilik yozuv",
      what: "Bitta musbat son berilgan. Uni ikkilik sanoq tizimida chiqar.",
      kirish: "Bitta musbat butun son.",
      chiqish: "Nol va birlardan iborat satr.",
      namuna: { stdin: ["10"], out: ["1010"] },
      tests: [["1"], ["2"], ["255"], ["64"]],
      solution: 'n = int(input())\ns = ""\nwhile n > 0:\n    s = str(n % 2) + s\n    n = n // 2\nprint(s)',
      hint: "Har qadamda 2 ga boʻlib, qoldiqni oldinga qoʻshib bor.",
    },
    {
      id: "faktorial",
      title: "Faktorial",
      what: "Bitta musbat son n berilgan. n! ni chiqar (1 dan n gacha sonlar koʻpaytmasi).",
      kirish: "Bitta musbat butun son.",
      chiqish: "Bitta son.",
      namuna: { stdin: ["5"], out: ["120"] },
      tests: [["1"], ["3"], ["10"], ["20"]],
      solution: "n = int(input())\ns = 1\nfor i in range(1, n + 1):\n    s = s * i\nprint(s)",
      hint: "Yigʻindidagidek, faqat s = 1 dan boshlanadi va koʻpaytiriladi.",
    },
    {
      id: "har-xil",
      title: "Nechta har xil son",
      what: "Bitta satrda bir nechta son berilgan. Ular orasida nechta har xil son borligini chiqar.",
      kirish: "Bitta satrda boʻsh joy bilan ajratilgan sonlar.",
      chiqish: "Bitta son.",
      namuna: { stdin: ["1 2 2 3 1"], out: ["3"] },
      tests: [["5"], ["7 7 7"], ["1 2 3 4"], ["10 2 10 2 5"]],
      solution: "a = input().split()\nb = []\nfor x in a:\n    b.append(int(x))\nb = sorted(b)\nsoni = 0\nfor i in range(len(b)):\n    if i == 0:\n        soni += 1\n    elif b[i] != b[i - 1]:\n        soni += 1\nprint(soni)",
      hint: "Saralasang, bir xil sonlar yonma-yon turadi.",
    },
    {
      id: "boluvchilar",
      title: "Boʻluvchilarni chiqar",
      what: "Bitta musbat son berilgan. Uning barcha boʻluvchilarini oʻsish tartibida, har satrda bittadan chiqar.",
      kirish: "Bitta musbat butun son.",
      chiqish: "Har satrda bitta boʻluvchi.",
      namuna: { stdin: ["12"], out: ["1", "2", "3", "4", "6", "12"] },
      tests: [["1"], ["7"], ["16"], ["30"]],
      solution: "n = int(input())\nfor i in range(1, n + 1):\n    if n % i == 0:\n        print(i)",
      hint: "1 dan n gacha yurib, qoldiq nolga teng boʻlsa chiqar.",
    },
  ];

  const LEVELS = [
    { id: "oson", title: "Oson", note: "Shart va sikl", problems: OSON },
    { id: "orta", title: "Oʻrta", note: "Raqamlar, roʻyxat va satr", problems: ORTA },
    { id: "qiyin", title: "Qiyin", note: "Bir nechta qadam", problems: QIYIN },
  ];

  const api = { LEVELS, OSON, ORTA, QIYIN };

  root.QK = root.QK || {};
  root.QK.bank = api;
  if (typeof module !== "undefined" && module.exports) module.exports = api;
})(typeof window !== "undefined" ? window : globalThis);
