// 35-o'yin: masalalar banki. Har masala qo'lda yozilgan (QOIDALAR §4.3 istisnosi).
// Har biri: shart, kirish/chiqish formati, ko'rinadigan namuna, yashirin testlar, namunali yechim va maslahat.
// tests/bank.test.js har bir yechimni barcha testlarda ishga tushirib tekshiradi.
(function (root) {
  "use strict";

  const OSON = [
    {
      id: "yigindi",
      rating: 100,
      tags: ["oʻzgaruvchi", "matematika"],
      title: "Ikki son yigʻindisi",
      what: "Ikkita butun son berilgan. Ularning yigʻindisini chiqar.",
      kirish: "Ikki satrda ikkita butun son.",
      chiqish: "Bitta son — yigʻindi.",
      namuna: { stdin: ["12", "30"], out: ["42"] },
      tests: [["5", "7"], ["0", "0"], ["-3", "10"], ["100", "250"]],
      solution: "a = int(input())\nb = int(input())\nprint(a + b)",
      hint: "Ikkita input() kerak, keyin qoʻshasan.",
    },
    {
      id: "kvadrat",
      rating: 100,
      tags: ["oʻzgaruvchi", "matematika"],
      title: "Kvadrat",
      what: "Bitta son berilgan. Uning kvadratini chiqar.",
      kirish: "Bitta butun son.",
      chiqish: "Bitta son — kvadrati.",
      namuna: { stdin: ["7"], out: ["49"] },
      tests: [["3"], ["0"], ["-4"], ["25"]],
      solution: "n = int(input())\nprint(n * n)",
      hint: "n * n yoki n ** 2.",
    },
    {
      id: "juft-toq",
      rating: 150,
      tags: ["shart", "raqamlar"],
      title: "Juft yoki toq",
      what: 'Bitta son berilgan. Agar u juft boʻlsa "juft", aks holda "toq" deb yoz.',
      kirish: "Bitta butun son.",
      chiqish: "juft yoki toq.",
      namuna: { stdin: ["10"], out: ["juft"] },
      tests: [["7"], ["0"], ["100"], ["13"]],
      solution: 'n = int(input())\nif n % 2 == 0:\n    print("juft")\nelse:\n    print("toq")',
      hint: "Juftlikni % 2 bilan tekshiriladi: qoldiq 0 boʻlsa — juft.",
    },
    {
      id: "eng-katta-3",
      rating: 200,
      tags: ["shart"],
      title: "Uchtadan kattasi",
      what: "Uchta son berilgan. Eng kattasini chiqar.",
      kirish: "Uch satrda uchta butun son.",
      chiqish: "Bitta son — eng kattasi.",
      namuna: { stdin: ["3", "9", "5"], out: ["9"] },
      tests: [["10", "2", "7"], ["1", "1", "1"], ["-5", "-2", "-9"], ["4", "4", "8"]],
      solution: "a = int(input())\nb = int(input())\nc = int(input())\nbest = a\nif b > best:\n    best = b\nif c > best:\n    best = c\nprint(best)",
      hint: "Birinchisini eng katta deb ol, keyin qolganlari bilan solishtir.",
    },
    {
      id: "yigindi-n",
      rating: 200,
      tags: ["for", "matematika"],
      title: "Birdan n gacha",
      what: "Bitta musbat son berilgan. 1 dan shu songacha (uning oʻzi ham kiradi) sonlar yigʻindisini chiqar.",
      kirish: "Bitta musbat butun son.",
      chiqish: "Bitta son — yigʻindi.",
      namuna: { stdin: ["5"], out: ["15"] },
      tests: [["1"], ["10"], ["100"], ["3"]],
      solution: "n = int(input())\ns = 0\nfor i in range(1, n + 1):\n    s += i\nprint(s)",
      hint: "range(1, n + 1) — n ning oʻzi ham kirishi uchun.",
    },
    {
      id: "oraliq-yigindi",
      rating: 250,
      tags: ["for", "matematika"],
      title: "a dan b gacha",
      what: "Ikkita son berilgan: a va b (a ≤ b). a dan b gacha (ikkalasi ham kiradi) sonlar yigʻindisini chiqar.",
      kirish: "Ikki satrda a va b.",
      chiqish: "Bitta son — yigʻindi.",
      namuna: { stdin: ["3", "6"], out: ["18"] },
      tests: [["1", "5"], ["7", "7"], ["0", "10"], ["10", "20"]],
      solution: "a = int(input())\nb = int(input())\ns = 0\nfor i in range(a, b + 1):\n    s += i\nprint(s)",
      hint: "a dan boshlab b + 1 gacha yur.",
    },
    {
      id: "musbat-manfiy",
      rating: 150,
      tags: ["shart"],
      title: "Musbat, manfiy yoki nol",
      what: 'Bitta son berilgan. "musbat", "manfiy" yoki "nol" deb yoz.',
      kirish: "Bitta butun son.",
      chiqish: "musbat, manfiy yoki nol.",
      namuna: { stdin: ["-7"], out: ["manfiy"] },
      tests: [["5"], ["0"], ["-1"], ["1000"]],
      solution: 'n = int(input())\nif n > 0:\n    print("musbat")\nelif n < 0:\n    print("manfiy")\nelse:\n    print("nol")',
      hint: "Uch holat — if, elif va else.",
    },
    {
      id: "yulduzcha",
      rating: 250,
      tags: ["for", "satr"],
      title: "Yulduzchalar",
      what: "Bitta musbat son berilgan. Shuncha satr chiqar: birinchi satrda 1 ta yulduzcha, ikkinchisida 2 ta va hokazo.",
      kirish: "Bitta musbat butun son.",
      chiqish: "n ta satr.",
      namuna: { stdin: ["3"], out: ["*", "**", "***"] },
      tests: [["1"], ["5"], ["2"], ["7"]],
      solution: 'n = int(input())\nfor i in range(1, n + 1):\n    print("*" * i)',
      hint: '"*" * i — yulduzchani i marta takrorlaydi.',
    },
    {
      id: "kiyim-variant",
      rating: 200,
      tags: ["matematika", "kombinatorika"],
      title: "Nechta kiyinish usuli",
      what: "a ta koʻylak va b ta shim bor. Har koʻylakni har shim bilan kiyish mumkin. Nechta kiyinish usuli bor?",
      kirish: "Ikki satrda a va b (1 ≤ a, b ≤ 1000).",
      chiqish: "Bitta son — usullar soni.",
      namuna: { stdin: ["3", "4"], out: ["12"] },
      tests: [["5", "2"], ["1", "1"], ["10", "10"], ["1000", "1000"]],
      solution: "a = int(input())\nb = int(input())\nprint(a * b)",
      hint: "Koʻpaytirish qoidasi: har qadamdagi tanlovlar koʻpaytiriladi.",
    },
  ];

  const ORTA = [
    {
      id: "raqamlar-yigindisi",
      rating: 300,
      tags: ["while", "raqamlar"],
      title: "Raqamlar yigʻindisi",
      what: "Bitta musbat son berilgan. Uning raqamlari yigʻindisini chiqar.",
      kirish: "Bitta musbat butun son.",
      chiqish: "Bitta son.",
      namuna: { stdin: ["5382"], out: ["18"] },
      tests: [["7"], ["100"], ["999"], ["10203"]],
      solution: "n = int(input())\ns = 0\nwhile n > 0:\n    s += n % 10\n    n = n // 10\nprint(s)",
      hint: "n % 10 — oxirgi raqam, n // 10 — qolgani.",
    },
    {
      id: "teskari-son",
      rating: 350,
      tags: ["while", "raqamlar"],
      title: "Teskari son",
      what: "Bitta musbat son berilgan. Uni teskari oʻgirib chiqar.",
      kirish: "Bitta musbat butun son.",
      chiqish: "Bitta son.",
      namuna: { stdin: ["1234"], out: ["4321"] },
      tests: [["7"], ["100"], ["9081"], ["10"]],
      solution: "n = int(input())\nt = 0\nwhile n > 0:\n    t = t * 10 + n % 10\n    n = n // 10\nprint(t)",
      hint: "Har qadamda: t = t * 10 + oxirgi raqam.",
    },
    {
      id: "farq",
      rating: 350,
      tags: ["roʻyxat", "shart"],
      title: "Eng katta va eng kichik farqi",
      what: "Bitta satrda bir nechta son berilgan. Eng katta va eng kichik sonning farqini chiqar.",
      kirish: "Bitta satrda boʻsh joy bilan ajratilgan sonlar.",
      chiqish: "Bitta son.",
      namuna: { stdin: ["3 9 5"], out: ["6"] },
      tests: [["7"], ["10 2 8 4"], ["5 5 5"], ["-3 10 0"]],
      solution: "a = input().split()\nbest = int(a[0])\nworst = int(a[0])\nfor x in a:\n    v = int(x)\n    if v > best:\n        best = v\n    if v < worst:\n        worst = v\nprint(best - worst)",
      hint: "Ikkita quti kerak: eng katta va eng kichik.",
    },
    {
      id: "juftlar-soni",
      rating: 300,
      tags: ["roʻyxat", "shart"],
      title: "Nechta juft",
      what: "Bitta satrda bir nechta son berilgan. Nechtasi juft ekanini chiqar.",
      kirish: "Bitta satrda boʻsh joy bilan ajratilgan sonlar.",
      chiqish: "Bitta son.",
      namuna: { stdin: ["1 2 3 4"], out: ["2"] },
      tests: [["7"], ["2 4 6"], ["1 3 5"], ["0 1 2 3 4 5"]],
      solution: "a = input().split()\nsoni = 0\nfor x in a:\n    if int(x) % 2 == 0:\n        soni += 1\nprint(soni)",
      hint: "split() dan keyin har boʻlakni int() bilan songa oʻgir.",
    },
    {
      id: "unlilar",
      rating: 300,
      tags: ["satr", "shart"],
      title: "Unli harflar",
      what: "Bitta soʻz berilgan. Undagi unli harflar (a, e, i, o, u) sonini chiqar.",
      kirish: "Bitta soʻz (kichik harflar bilan).",
      chiqish: "Bitta son.",
      namuna: { stdin: ["qabila"], out: ["3"] },
      tests: [["python"], ["aeiou"], ["kkk"], ["dastur"]],
      solution: 'soz = input()\nsoni = 0\nfor harf in soz:\n    if harf in "aeiou":\n        soni += 1\nprint(soni)',
      hint: 'harf in "aeiou" — harf unlilar orasida bormi.',
    },
    {
      id: "boluvchilar-soni",
      rating: 350,
      tags: ["for", "matematika"],
      title: "Boʻluvchilar soni",
      what: "Bitta musbat son berilgan. Uning nechta boʻluvchisi borligini chiqar.",
      kirish: "Bitta musbat butun son.",
      chiqish: "Bitta son.",
      namuna: { stdin: ["12"], out: ["6"] },
      tests: [["1"], ["7"], ["36"], ["100"]],
      solution: "n = int(input())\nsoni = 0\nfor i in range(1, n + 1):\n    if n % i == 0:\n        soni += 1\nprint(soni)",
      hint: "1 dan n gacha yurib, qoldiq nolga tengini sana.",
    },
    {
      id: "fibonachchi",
      rating: 450,
      tags: ["for", "oʻzgaruvchi"],
      title: "Fibonachchi",
      what: "Bitta son n berilgan. Fibonachchi ketma-ketligining n-hadini chiqar. Ketma-ketlik: 0, 1, 1, 2, 3, 5, … (1-had — 0).",
      kirish: "Bitta musbat butun son n.",
      chiqish: "Bitta son.",
      namuna: { stdin: ["7"], out: ["8"] },
      tests: [["1"], ["2"], ["10"], ["20"]],
      solution: "n = int(input())\na = 0\nb = 1\nfor i in range(n - 1):\n    a, b = b, a + b\nprint(a)",
      hint: "Ikki qutini almashtirib bor: a, b = b, a + b.",
    },
    {
      id: "palindrom",
      rating: 400,
      tags: ["satr", "shart"],
      title: "Palindrom",
      what: 'Bitta soʻz berilgan. Agar u teskari oʻqilganda ham bir xil boʻlsa "ha", aks holda "yoʻq" deb yoz.',
      kirish: "Bitta soʻz.",
      chiqish: "ha yoki yoʻq.",
      namuna: { stdin: ["abba"], out: ["ha"] },
      tests: [["qabila"], ["a"], ["aba"], ["python"]],
      solution: 'soz = input()\nt = ""\nfor harf in soz:\n    t = harf + t\nif t == soz:\n    print("ha")\nelse:\n    print("yoʻq")',
      hint: "Avval soʻzni teskari yasab ol, keyin solishtir.",
    },
    {
      id: "qol-berish",
      rating: 400,
      tags: ["matematika", "kombinatorika"],
      title: "Qoʻl berib koʻrishish",
      what: "Xonada n kishi bor. Har ikkisi bir martadan qoʻl berib koʻrishdi. Nechta qoʻl berish boʻldi?",
      kirish: "Bitta butun son n (1 ≤ n ≤ 100000).",
      chiqish: "Bitta son — qoʻl berishlar soni.",
      namuna: { stdin: ["5"], out: ["10"] },
      tests: [["1"], ["2"], ["100"], ["100000"]],
      solution: "n = int(input())\nprint(n * (n - 1) // 2)",
      hint: "Har kishi qolgan n−1 kishi bilan koʻrishadi, lekin har juftlik ikki marta sanaladi.",
    },
    {
      id: "jamoa-soni",
      rating: 500,
      tags: ["for", "kombinatorika"],
      title: "Jamoa tanlash",
      what: "n boladan k kishilik jamoa tuziladi. Jamoada tartib muhim emas. Nechta xil jamoa bor?",
      kirish: "Ikki satrda n va k (0 ≤ k ≤ n ≤ 30).",
      chiqish: "Bitta son — jamoalar soni.",
      namuna: { stdin: ["5", "3"], out: ["10"] },
      tests: [["6", "0"], ["7", "7"], ["10", "2"], ["30", "15"]],
      solution: "n = int(input())\nk = int(input())\nnatija = 1\nfor i in range(k):\n    natija = natija * (n - i)\nfor i in range(1, k + 1):\n    natija = natija // i\nprint(natija)",
      hint: "Avval n × (n−1) × … (k ta koʻpaytuvchi), keyin k! ga boʻl.",
    },
    {
      id: "kaptarxona",
      rating: 400,
      tags: ["matematika", "kombinatorika"],
      title: "Eng toʻla quti",
      what: "n ta xat k ta pochta qutisiga tashlandi. Qanday tashlanganidan qatʼi nazar, eng toʻla qutida kamida nechta xat bor?",
      kirish: "Ikki satrda n va k (1 ≤ n, k ≤ 1000000).",
      chiqish: "Bitta son — kafolatlangan eng kichik javob.",
      namuna: { stdin: ["13", "12"], out: ["2"] },
      tests: [["4", "4"], ["25", "12"], ["1", "1000"], ["1000000", "7"]],
      solution: "n = int(input())\nk = int(input())\nprint((n + k - 1) // k)",
      hint: "Dirixle printsipi: boʻlishni yuqoriga yumalatish kerak — (n + k − 1) // k.",
    },
  ];

  const QIYIN = [
    {
      id: "tubmi",
      rating: 550,
      tags: ["while", "matematika"],
      title: "Tub sonmi",
      what: 'Bitta son berilgan. Agar u tub son boʻlsa "ha", aks holda "yoʻq" deb yoz. (Tub son — 1 va oʻzidan boshqa boʻluvchisi yoʻq, 1 dan katta son.)',
      kirish: "Bitta butun son.",
      chiqish: "ha yoki yoʻq.",
      namuna: { stdin: ["13"], out: ["ha"] },
      tests: [["1"], ["2"], ["9"], ["97"], ["100"]],
      solution: 'n = int(input())\ntub = True\nif n < 2:\n    tub = False\nd = 2\nwhile d * d <= n:\n    if n % d == 0:\n        tub = False\n    d += 1\nif tub:\n    print("ha")\nelse:\n    print("yoʻq")',
      hint: "Boʻluvchini d * d <= n gacha qidirsang yetadi. 1 va 0 tub emas.",
    },
    {
      id: "tublar-soni",
      rating: 650,
      tags: ["for", "while", "matematika"],
      title: "Nechta tub son",
      what: "Bitta musbat son n berilgan. 2 dan n gacha (n ham kiradi) nechta tub son borligini chiqar.",
      kirish: "Bitta musbat butun son.",
      chiqish: "Bitta son.",
      namuna: { stdin: ["10"], out: ["4"] },
      tests: [["1"], ["2"], ["20"], ["50"]],
      solution: "n = int(input())\nsoni = 0\nfor x in range(2, n + 1):\n    tub = True\n    d = 2\n    while d * d <= x:\n        if x % d == 0:\n            tub = False\n        d += 1\n    if tub:\n        soni += 1\nprint(soni)",
      hint: "Har bir sonni alohida tekshir — ichma-ich sikl kerak boʻladi.",
    },
    {
      id: "ekub",
      rating: 600,
      tags: ["while", "matematika"],
      title: "Eng katta umumiy boʻluvchi",
      what: "Ikkita musbat son berilgan. Ularning eng katta umumiy boʻluvchisini chiqar.",
      kirish: "Ikki satrda ikkita musbat son.",
      chiqish: "Bitta son.",
      namuna: { stdin: ["12", "18"], out: ["6"] },
      tests: [["7", "13"], ["100", "75"], ["5", "5"], ["36", "12"]],
      solution: "a = int(input())\nb = int(input())\nwhile b > 0:\n    r = a % b\n    a = b\n    b = r\nprint(a)",
      hint: "Evklid usuli: kattasini kichigiga boʻlib, qoldiq bilan davom et.",
    },
    {
      id: "ikkinchi-katta",
      rating: 500,
      tags: ["roʻyxat", "saralash"],
      title: "Ikkinchi eng katta",
      what: "Bitta satrda bir nechta har xil son berilgan. Ikkinchi eng kattasini chiqar.",
      kirish: "Bitta satrda kamida ikkita har xil son.",
      chiqish: "Bitta son.",
      namuna: { stdin: ["3 9 5"], out: ["5"] },
      tests: [["10 2"], ["1 7 4 9 2"], ["100 50 75"], ["-3 -1 -7"]],
      solution: "a = input().split()\nb = []\nfor x in a:\n    b.append(int(x))\nb = sorted(b)\nprint(b[len(b) - 2])",
      hint: "Saralangan roʻyxatda oxiridan ikkinchisi kerak.",
    },
    {
      id: "ikkilik",
      rating: 600,
      tags: ["while", "satr", "raqamlar"],
      title: "Ikkilik yozuv",
      what: "Bitta musbat son berilgan. Uni ikkilik sanoq tizimida chiqar.",
      kirish: "Bitta musbat butun son.",
      chiqish: "Nol va birlardan iborat satr.",
      namuna: { stdin: ["10"], out: ["1010"] },
      tests: [["1"], ["2"], ["255"], ["64"]],
      solution: 'n = int(input())\ns = ""\nwhile n > 0:\n    s = str(n % 2) + s\n    n = n // 2\nprint(s)',
      hint: "Har qadamda 2 ga boʻlib, qoldiqni oldinga qoʻshib bor.",
    },
    {
      id: "faktorial",
      rating: 450,
      tags: ["for", "matematika", "kombinatorika"],
      title: "Faktorial",
      what: "Bitta musbat son n berilgan. n! ni chiqar (1 dan n gacha sonlar koʻpaytmasi).",
      kirish: "Bitta musbat butun son.",
      chiqish: "Bitta son.",
      namuna: { stdin: ["5"], out: ["120"] },
      tests: [["1"], ["3"], ["10"], ["20"]],
      solution: "n = int(input())\ns = 1\nfor i in range(1, n + 1):\n    s = s * i\nprint(s)",
      hint: "Yigʻindidagidek, faqat s = 1 dan boshlanadi va koʻpaytiriladi.",
    },
    {
      id: "har-xil",
      rating: 650,
      tags: ["roʻyxat", "saralash"],
      title: "Nechta har xil son",
      what: "Bitta satrda bir nechta son berilgan. Ular orasida nechta har xil son borligini chiqar.",
      kirish: "Bitta satrda boʻsh joy bilan ajratilgan sonlar.",
      chiqish: "Bitta son.",
      namuna: { stdin: ["1 2 2 3 1"], out: ["3"] },
      tests: [["5"], ["7 7 7"], ["1 2 3 4"], ["10 2 10 2 5"]],
      solution: "a = input().split()\nb = []\nfor x in a:\n    b.append(int(x))\nb = sorted(b)\nsoni = 0\nfor i in range(len(b)):\n    if i == 0:\n        soni += 1\n    elif b[i] != b[i - 1]:\n        soni += 1\nprint(soni)",
      hint: "Saralasang, bir xil sonlar yonma-yon turadi.",
    },
    {
      id: "boluvchilar",
      rating: 400,
      tags: ["for", "matematika"],
      title: "Boʻluvchilarni chiqar",
      what: "Bitta musbat son berilgan. Uning barcha boʻluvchilarini oʻsish tartibida, har satrda bittadan chiqar.",
      kirish: "Bitta musbat butun son.",
      chiqish: "Har satrda bitta boʻluvchi.",
      namuna: { stdin: ["12"], out: ["1", "2", "3", "4", "6", "12"] },
      tests: [["1"], ["7"], ["16"], ["30"]],
      solution: "n = int(input())\nfor i in range(1, n + 1):\n    if n % i == 0:\n        print(i)",
      hint: "1 dan n gacha yurib, qoldiq nolga teng boʻlsa chiqar.",
    },
    {
      id: "paskal-qator",
      rating: 600,
      tags: ["roʻyxat", "kombinatorika"],
      title: "Paskal qatori",
      what: "Paskal uchburchagining n-qatorini chiqar. Sonlar bitta satrda, boʻsh joy bilan ajratilgan. 0-qator — bitta 1.",
      kirish: "Bitta butun son n (0 ≤ n ≤ 30).",
      chiqish: "n-qator sonlari bitta satrda.",
      namuna: { stdin: ["5"], out: ["1 5 10 10 5 1"] },
      tests: [["0"], ["1"], ["10"], ["30"]],
      solution: "n = int(input())\na = [1]\nfor i in range(n):\n    yangi = [1]\n    for j in range(len(a) - 1):\n        yangi.append(a[j] + a[j + 1])\n    yangi.append(1)\n    a = yangi\njavob = str(a[0])\nfor i in range(1, len(a)):\n    javob = javob + \" \" + str(a[i])\nprint(javob)",
      hint: "Har qator chekkalari 1, ichkarisi — oldingi qatordagi qoʻshni ikkitaning yigʻindisi.",
    },
    {
      id: "parol-soni",
      rating: 700,
      tags: ["for", "kombinatorika"],
      title: "Nechta parol bor",
      what: "Alifboda a ta belgi bor. Uzunligi 1 dan n gacha boʻlgan nechta parol yasash mumkin? (Belgilar takrorlanishi mumkin.)",
      kirish: "Ikki satrda a va n (1 ≤ a ≤ 100, 1 ≤ n ≤ 10).",
      chiqish: "Bitta son — parollar soni.",
      namuna: { stdin: ["2", "3"], out: ["14"] },
      tests: [["1", "5"], ["10", "1"], ["26", "4"], ["100", "10"]],
      solution: "a = int(input())\nn = int(input())\njami = 0\ndaraja = 1\nfor i in range(n):\n    daraja = daraja * a\n    jami = jami + daraja\nprint(jami)",
      hint: "Uzunligi i boʻlgan parollar soni — a ning i-darajasi. Hammasini qoʻshish kerak (qoʻshish qoidasi).",
    },
    {
      id: "tanga-gerb",
      rating: 800,
      tags: ["for", "kombinatorika"],
      title: "Tanga va gerb",
      what: "Tanga n marta tashlandi. Aynan k martasida gerb tushishining nechta xil varianti bor?",
      kirish: "Ikki satrda n va k (0 ≤ k ≤ n ≤ 30).",
      chiqish: "Bitta son — variantlar soni.",
      namuna: { stdin: ["4", "2"], out: ["6"] },
      tests: [["1", "0"], ["5", "5"], ["10", "3"], ["30", "15"]],
      solution: "n = int(input())\nk = int(input())\nnatija = 1\nfor i in range(k):\n    natija = natija * (n - i)\nfor i in range(1, k + 1):\n    natija = natija // i\nprint(natija)",
      hint: "Qaysi tashlashlar gerb boʻlishini tanlaymiz — bu C(n, k).",
    },
  ];


  // Teglar — bizning mavzularimiz: masala qaysi darslarga tayanadi
  const TAGS = ["oʻzgaruvchi", "matematika", "shart", "while", "for", "roʻyxat", "satr", "raqamlar", "saralash", "funksiya", "kombinatorika"];

  // Codeforces'dan olingan masalalar. SHARTLAR OʻZIMIZNIKI — asl matn koʻchirilmagan,
  // faqat masalaning gʻoyasi olingan va manbaga havola qoʻyilgan (mualliflik huquqi).
  // rating va cfTags — Codeforces API dan olingan haqiqiy qiymatlar (2026-09-30).
  const CF = [
    {
      id: "cf-tarvuz",
      tartib: 1,
      title: "Tarvuzni boʻlish",
      what: "Tarvuzning ogʻirligi w kilogramm. Uni ikkita boʻlakka boʻlmoqchimiz, har bir boʻlakning ogʻirligi juft son va noldan katta boʻlsin. Shunday boʻlish mumkinmi?",
      kirish: "Bitta butun son w (1 ≤ w ≤ 100).",
      chiqish: 'Mumkin boʻlsa "ha", aks holda "yoʻq".',
      namuna: { stdin: ["8"], out: ["ha"] },
      tests: [["2"], ["1"], ["100"], ["3"], ["4"]],
      solution: 'w = int(input())\nif w % 2 == 0 and w > 2:\n    print("ha")\nelse:\n    print("yoʻq")',
      hint: "Juft sonni ikki juft boʻlakka boʻlish mumkin — lekin 2 ni boʻlib boʻlmaydi (0 boʻlak chiqadi).",
      rating: 800,
      tags: ["shart", "matematika"],
      manba: { kod: "4A", nom: "Watermelon", cfTags: ["brute force", "math"], url: "https://codeforces.com/problemset/problem/4/A" },
      animatsiya: null,
    },
    {
      id: "cf-domino",
      tartib: 2,
      title: "Nechta domino sigʻadi",
      what: "Oʻlchami m × n boʻlgan toʻrtburchak taxta bor. Unga oʻlchami 1 × 2 boʻlgan dominolarni bir-birining ustiga chiqmasdan, taxtadan tashqariga chiqmasdan joylaymiz. Eng koʻpi bilan nechta domino sigʻadi?",
      kirish: "Bitta satrda ikkita son: m va n (1 ≤ m, n ≤ 16).",
      chiqish: "Bitta son — dominolar soni.",
      namuna: { stdin: ["2 4"], out: ["4"] },
      tests: [["1 1"], ["3 3"], ["16 16"], ["1 5"], ["5 1"]],
      solution: "s = input().split()\nm = int(s[0])\nn = int(s[1])\nprint(m * n // 2)",
      hint: "Har domino 2 katakni egallaydi. Kataklar soni toq boʻlsa, bittasi boʻsh qoladi.",
      rating: 800,
      tags: ["matematika"],
      manba: { kod: "50A", nom: "Domino piling", cfTags: ["greedy", "math"], url: "https://codeforces.com/problemset/problem/50/A" },
      animatsiya: null,
    },
    {
      id: "cf-fil",
      tartib: 3,
      title: "Filning qadamlari",
      what: "Fil sonlar oʻqining 0 nuqtasida turibdi. Uning doʻsti x nuqtada. Fil bir qadamda 1, 2, 3, 4 yoki 5 pogʻona oʻngga yura oladi. Doʻstiga yetib borish uchun unga eng kamida nechta qadam kerak?",
      kirish: "Bitta butun son x (1 ≤ x ≤ 1 000 000).",
      chiqish: "Bitta son — qadamlar soni.",
      namuna: { stdin: ["12"], out: ["3"] },
      tests: [["5"], ["1"], ["6"], ["1000000"], ["10"]],
      solution: "x = int(input())\nprint((x + 4) // 5)",
      hint: "Eng tez yoʻl — 5 pogʻonadan yurish. Oxirida qolgan masofa uchun yana bitta qadam kerak boʻlishi mumkin.",
      rating: 800,
      tags: ["matematika"],
      manba: { kod: "617A", nom: "Elephant", cfTags: ["math"], url: "https://codeforces.com/problemset/problem/617/A" },
      animatsiya: null,
    },
    {
      id: "cf-ukalar",
      tartib: 4,
      title: "Ukam qachon oʻzib ketadi",
      what: "Kichik ukaning vazni a, kattasiniki b (a ≤ b). Har yili kichigining vazni 3 baravar, kattasiniki 2 baravar oshadi. Kichigining vazni kattasinikidan qatʼiy koʻp boʻlishi uchun necha yil kerak?",
      kirish: "Bitta satrda ikkita son: a va b (1 ≤ a ≤ b ≤ 10).",
      chiqish: "Bitta son — yillar soni.",
      namuna: { stdin: ["4 7"], out: ["2"] },
      tests: [["1 1"], ["10 10"], ["1 10"], ["4 9"], ["2 3"]],
      solution: "s = input().split()\na = int(s[0])\nb = int(s[1])\nyil = 0\nwhile a <= b:\n    a = a * 3\n    b = b * 2\n    yil += 1\nprint(yil)",
      hint: "Sikl a > b boʻlguncha davom etadi. Har aylanishda ikkala vaznni ham yangila.",
      rating: 800,
      tags: ["while", "oʻzgaruvchi"],
      manba: { kod: "791A", nom: "Bear and Big Brother", cfTags: ["implementation"], url: "https://codeforces.com/problemset/problem/791/A" },
      animatsiya: null,
    },
    {
      id: "cf-notogri-ayirish",
      tartib: 5,
      title: "Notoʻgʻri ayirish",
      what: "Tanya sonni bittaga kamaytirishni bilmaydi. U shunday qiladi: agar sonning oxirgi raqami 0 boʻlsa, oxirgi raqamni oʻchiradi; aks holda sondan 1 ayiradi. Tanya shu amalni k marta bajarsa, qanday son qoladi?",
      kirish: "Bitta satrda ikkita son: n va k (2 ≤ n ≤ 10⁹, 1 ≤ k ≤ 50). Natija doim musbat boʻladi.",
      chiqish: "Bitta son.",
      namuna: { stdin: ["512 4"], out: ["50"] },
      tests: [["1000000000 9"], ["100 1"], ["2 1"], ["10 1"], ["999 3"]],
      solution: "s = input().split()\nn = int(s[0])\nk = int(s[1])\nfor i in range(k):\n    if n % 10 == 0:\n        n = n // 10\n    else:\n        n = n - 1\nprint(n)",
      hint: "Oxirgi raqamni n % 10 beradi, oʻchirishni n // 10 qiladi.",
      rating: 800,
      tags: ["for", "raqamlar", "shart"],
      manba: { kod: "977A", nom: "Wrong Subtraction", cfTags: ["implementation"], url: "https://codeforces.com/problemset/problem/977/A" },
      animatsiya: null,
    },
    {
      id: "cf-jamoa",
      tartib: 8,
      title: "Jamoa qaroriga koʻra",
      what: "Uch doʻst olimpiadada qatnashmoqda. Har masala uchun har biri oʻzining ishonchini bildiradi: 1 — yechimni bilaman, 0 — bilmayman. Agar kamida ikkitasi ishonsa, jamoa shu masalani yozishga kirishadi. Nechta masalani yozishadi?",
      kirish: "Birinchi satrda n (1 ≤ n ≤ 1000) — masalalar soni. Keyingi n satrda uchtadan 0 yoki 1.",
      chiqish: "Bitta son — yoziladigan masalalar soni.",
      namuna: { stdin: ["3", "1 1 0", "1 1 1", "1 0 0"], out: ["2"] },
      tests: [["1", "0 0 0"], ["1", "1 1 1"], ["2", "1 0 1", "0 1 1"], ["4", "0 0 0", "1 1 0", "0 1 1", "1 0 0"]],
      solution: "n = int(input())\nsoni = 0\nfor i in range(n):\n    s = input().split()\n    yigindi = int(s[0]) + int(s[1]) + int(s[2])\n    if yigindi >= 2:\n        soni += 1\nprint(soni)",
      hint: "Har satrni alohida input() bilan oʻqi. Uch sonning yigʻindisi 2 dan kam boʻlmasa — sanaysan.",
      rating: 800,
      tags: ["for", "shart", "roʻyxat"],
      manba: { kod: "231A", nom: "Team", cfTags: ["brute force", "greedy"], url: "https://codeforces.com/problemset/problem/231/A" },
      animatsiya: null,
    },
    {
      id: "cf-toshlar",
      tartib: 6,
      title: "Stol ustidagi toshlar",
      what: "Stolda bir qator tosh turibdi, har biri qizil (R), yashil (G) yoki koʻk (B). Yonma-yon turgan ikki tosh bir xil rangda boʻlmasligi kerak. Shu shart bajarilishi uchun eng kamida nechta toshni olib tashlash kerak?",
      kirish: "Birinchi satrda n (1 ≤ n ≤ 50). Ikkinchi satrda n ta harfdan iborat satr: faqat R, G va B.",
      chiqish: "Bitta son — olib tashlanadigan toshlar soni.",
      namuna: { stdin: ["3", "RRG"], out: ["1"] },
      tests: [["1", "R"], ["5", "RGBGR"], ["4", "RRRR"], ["6", "BBGGRR"], ["2", "RG"]],
      solution: "n = int(input())\ns = input()\nsoni = 0\nfor i in range(1, len(s)):\n    if s[i] == s[i - 1]:\n        soni += 1\nprint(soni)",
      hint: "Har harfni oʻzidan oldingisi bilan solishtir. Birinchi harfning oldingisi yoʻq — shuning uchun sikl 1 dan boshlanadi.",
      rating: 800,
      tags: ["satr", "for", "shart"],
      manba: { kod: "266A", nom: "Stones on the Table", cfTags: ["implementation"], url: "https://codeforces.com/problemset/problem/266/A" },
      animatsiya: null,
    },
    {
      id: "cf-hisoblagich",
      tartib: 7,
      title: "Gʻalati hisoblagich",
      what: "Boshida x = 0. Sizga n ta buyruq beriladi, har biri x ni bittaga oshiradi yoki bittaga kamaytiradi. Buyruq uch belgidan iborat: ichida ++ boʻlsa — oshirish, -- boʻlsa — kamaytirish (masalan ++x, x++, --x, x--). Oxirida x qanday boʻladi?",
      kirish: "Birinchi satrda n (1 ≤ n ≤ 150). Keyingi n satrda bittadan buyruq.",
      chiqish: "Bitta son — oxirgi x.",
      namuna: { stdin: ["2", "++x", "--x"], out: ["0"] },
      tests: [["1", "x++"], ["1", "x--"], ["3", "++x", "++x", "x++"], ["4", "--x", "x--", "++x", "x++"]],
      solution: 'n = int(input())\nx = 0\nfor i in range(n):\n    buyruq = input()\n    if "+" in buyruq:\n        x += 1\n    else:\n        x -= 1\nprint(x)',
      hint: 'Butun buyruqni tekshirish shart emas: "+" in buyruq — ichida plus bormi degani.',
      rating: 800,
      tags: ["for", "satr", "shart"],
      manba: { kod: "282A", nom: "Bit++", cfTags: ["implementation"], url: "https://codeforces.com/problemset/problem/282/A" },
      animatsiya: null,
    },
    {
      id: "cf-satr-solishtirish",
      tartib: 9,
      title: "Ikki soʻzni solishtirish",
      what: "Ikkita bir xil uzunlikdagi soʻz berilgan. Ularni katta-kichik harf farqiga eʼtibor bermay solishtiring: birinchisi alifboda oldin kelsa −1, keyin kelsa 1, teng boʻlsa 0 chiqaring.",
      kirish: "Ikki satrda ikkita soʻz (uzunligi 100 dan oshmaydi, faqat lotin harflari).",
      chiqish: "−1, 0 yoki 1.",
      namuna: { stdin: ["aaaa", "aaaA"], out: ["0"] },
      tests: [["abs", "Abz"], ["abcdefg", "AbCdEfF"], ["a", "b"], ["zz", "ZZ"], ["Ba", "ab"]],
      solution: "a = input().lower()\nb = input().lower()\nif a < b:\n    print(-1)\nelif a > b:\n    print(1)\nelse:\n    print(0)",
      hint: "Avval ikkala soʻzni kichik harfga oʻgir (lower), keyin oddiy solishtirish belgilari bilan solishtir.",
      rating: 800,
      tags: ["satr", "shart"],
      manba: { kod: "112A", nom: "Petya and Strings", cfTags: ["implementation", "strings"], url: "https://codeforces.com/problemset/problem/112/A" },
      animatsiya: null,
    },
    {
      id: "cf-har-xil-harf",
      tartib: 10,
      title: "Ismdagi har xil harflar",
      what: 'Bitta soʻz berilgan. Undagi har xil harflar sonini toping: agar bu son juft boʻlsa "juft", aks holda "toq" deb yozing.',
      kirish: "Bitta soʻz (uzunligi 100 dan oshmaydi, kichik lotin harflari).",
      chiqish: "juft yoki toq.",
      namuna: { stdin: ["bananas"], out: ["juft"] },
      tests: [["a"], ["ab"], ["aabbcc"], ["qabila"], ["xxxxx"]],
      solution: 'soz = input()\nb = sorted(soz)\nsoni = 0\nfor i in range(len(b)):\n    if i == 0:\n        soni += 1\n    elif b[i] != b[i - 1]:\n        soni += 1\nif soni % 2 == 0:\n    print("juft")\nelse:\n    print("toq")',
      hint: "Harflarni saralasang, bir xillari yonma-yon turadi — shunda har xillarini sanash oson.",
      rating: 800,
      tags: ["satr", "saralash", "for"],
      manba: { kod: "236A", nom: "Boy or Girl", cfTags: ["brute force", "implementation", "strings"], url: "https://codeforces.com/problemset/problem/236/A" },
      animatsiya: null,
    },
  ];

  const LEVELS = [
    { id: "oson", title: "Oson", note: "Shart va sikl", problems: OSON },
    { id: "orta", title: "Oʻrta", note: "Raqamlar, roʻyxat va satr", problems: ORTA },
    { id: "qiyin", title: "Qiyin", note: "Bir nechta qadam", problems: QIYIN },
    { id: "cf", title: "Codeforces", note: "Haqiqiy olimpiada masalalari (reyting 800)", problems: CF },
  ];

  const api = { LEVELS, TAGS, OSON, ORTA, QIYIN, CF };

  root.QK = root.QK || {};
  root.QK.bank = api;
  if (typeof module !== "undefined" && module.exports) module.exports = api;
})(typeof window !== "undefined" ? window : globalThis);
