// 35-o'yin: masalalar banki. Har masala qo'lda yozilgan (QOIDALAR §4.3 istisnosi).
// Har biri: shart, kirish/chiqish formati, ko'rinadigan namuna, yashirin testlar, namunali yechim va maslahat.
// tests/bank.test.js har bir yechimni barcha testlarda ishga tushirib tekshiradi.
(function (root) {
  "use strict";

  const OSON = [
    {
      id: "yigindi",
      rating: 100,
      tags: ["oʻzgaruvchi", "matematika"],
      title: "Ikki son yigʻindisi",
      what: "Ikkita butun son berilgan. Ularning yigʻindisini chiqar.",
      kirish: "Ikki satrda ikkita butun son.",
      chiqish: "Bitta son — yigʻindi.",
      namuna: { stdin: ["12", "30"], out: ["42"] },
      tests: [["5", "7"], ["0", "0"], ["-3", "10"], ["100", "250"], ["-1000000", "-1"], ["123456", "654321"]],
      solution: "a = int(input())\nb = int(input())\nprint(a + b)",
      hint: "Ikkita input() kerak, keyin qoʻshasan.",
    },
    {
      id: "kvadrat",
      rating: 100,
      tags: ["oʻzgaruvchi", "matematika"],
      title: "Kvadrat",
      what: "Bitta son berilgan. Uning kvadratini chiqar.",
      kirish: "Bitta butun son.",
      chiqish: "Bitta son — kvadrati.",
      namuna: { stdin: ["7"], out: ["49"] },
      tests: [["3"], ["0"], ["-4"], ["25"], ["-1"], ["1000000"]],
      solution: "n = int(input())\nprint(n * n)",
      hint: "n * n yoki n ** 2.",
    },
    {
      id: "juft-toq",
      rating: 150,
      tags: ["shart", "raqamlar"],
      title: "Juft yoki toq",
      what: 'Bitta son berilgan. Agar u juft boʻlsa "juft", aks holda "toq" deb yoz.',
      kirish: "Bitta butun son.",
      chiqish: "juft yoki toq.",
      namuna: { stdin: ["10"], out: ["juft"] },
      tests: [["7"], ["0"], ["100"], ["13"], ["-7"], ["-4"]],
      solution: 'n = int(input())\nif n % 2 == 0:\n    print("juft")\nelse:\n    print("toq")',
      hint: "Juftlikni % 2 bilan tekshiriladi: qoldiq 0 boʻlsa — juft.",
    },
    {
      id: "eng-katta-3",
      rating: 200,
      tags: ["shart"],
      title: "Uchtadan kattasi",
      what: "Uchta son berilgan. Eng kattasini chiqar.",
      kirish: "Uch satrda uchta butun son.",
      chiqish: "Bitta son — eng kattasi.",
      namuna: { stdin: ["3", "9", "5"], out: ["9"] },
      tests: [["10", "2", "7"], ["1", "1", "1"], ["-5", "-2", "-9"], ["4", "4", "8"], ["-1", "-1", "-1"], ["9", "2", "9"], ["-100", "0", "-50"]],
      solution: "a = int(input())\nb = int(input())\nc = int(input())\nbest = a\nif b > best:\n    best = b\nif c > best:\n    best = c\nprint(best)",
      hint: "Birinchisini eng katta deb ol, keyin qolganlari bilan solishtir.",
    },
    {
      id: "yigindi-n",
      rating: 200,
      tags: ["for", "matematika"],
      title: "Birdan n gacha",
      what: "Bitta musbat son berilgan. 1 dan shu songacha (uning oʻzi ham kiradi) sonlar yigʻindisini chiqar.",
      kirish: "Bitta musbat butun son.",
      chiqish: "Bitta son — yigʻindi.",
      namuna: { stdin: ["5"], out: ["15"] },
      tests: [["1"], ["10"], ["100"], ["3"], ["2"], ["1000"]],
      solution: "n = int(input())\ns = 0\nfor i in range(1, n + 1):\n    s += i\nprint(s)",
      hint: "range(1, n + 1) — n ning oʻzi ham kirishi uchun.",
    },
    {
      id: "oraliq-yigindi",
      rating: 250,
      tags: ["for", "matematika"],
      title: "a dan b gacha",
      what: "Ikkita son berilgan: a va b (a ≤ b). a dan b gacha (ikkalasi ham kiradi) sonlar yigʻindisini chiqar.",
      kirish: "Ikki satrda a va b.",
      chiqish: "Bitta son — yigʻindi.",
      namuna: { stdin: ["3", "6"], out: ["18"] },
      tests: [["1", "5"], ["7", "7"], ["0", "10"], ["10", "20"], ["-5", "5"], ["-3", "-1"], ["0", "0"]],
      solution: "a = int(input())\nb = int(input())\ns = 0\nfor i in range(a, b + 1):\n    s += i\nprint(s)",
      hint: "a dan boshlab b + 1 gacha yur.",
    },
    {
      id: "musbat-manfiy",
      rating: 150,
      tags: ["shart"],
      title: "Musbat, manfiy yoki nol",
      what: 'Bitta son berilgan. "musbat", "manfiy" yoki "nol" deb yoz.',
      kirish: "Bitta butun son.",
      chiqish: "musbat, manfiy yoki nol.",
      namuna: { stdin: ["-7"], out: ["manfiy"] },
      tests: [["5"], ["0"], ["-1"], ["1000"], ["-1000"], ["1"]],
      solution: 'n = int(input())\nif n > 0:\n    print("musbat")\nelif n < 0:\n    print("manfiy")\nelse:\n    print("nol")',
      hint: "Uch holat — if, elif va else.",
    },
    {
      id: "yulduzcha",
      rating: 250,
      tags: ["for", "satr"],
      title: "Yulduzchalar",
      what: "Bitta musbat son berilgan. Shuncha satr chiqar: birinchi satrda 1 ta yulduzcha, ikkinchisida 2 ta va hokazo.",
      kirish: "Bitta musbat butun son.",
      chiqish: "n ta satr.",
      namuna: { stdin: ["3"], out: ["*", "**", "***"] },
      tests: [["1"], ["5"], ["2"], ["7"], ["10"], ["4"]],
      solution: 'n = int(input())\nfor i in range(1, n + 1):\n    print("*" * i)',
      hint: '"*" * i — yulduzchani i marta takrorlaydi.',
    },
    {
      id: "kiyim-variant",
      rating: 200,
      tags: ["matematika", "kombinatorika"],
      title: "Nechta kiyinish usuli",
      what: "a ta koʻylak va b ta shim bor. Har koʻylakni har shim bilan kiyish mumkin. Nechta kiyinish usuli bor?",
      kirish: "Ikki satrda a va b (1 ≤ a, b ≤ 1000).",
      chiqish: "Bitta son — usullar soni.",
      namuna: { stdin: ["3", "4"], out: ["12"] },
      tests: [["5", "2"], ["1", "1"], ["10", "10"], ["1000", "1000"], ["1", "1000"], ["7", "3"]],
      solution: "a = int(input())\nb = int(input())\nprint(a * b)",
      hint: "Koʻpaytirish qoidasi: har qadamdagi tanlovlar koʻpaytiriladi.",
    },
  ];

  const ORTA = [
    {
      id: "raqamlar-yigindisi",
      rating: 300,
      tags: ["while", "raqamlar"],
      title: "Raqamlar yigʻindisi",
      what: "Bitta musbat son berilgan. Uning raqamlari yigʻindisini chiqar.",
      kirish: "Bitta musbat butun son.",
      chiqish: "Bitta son.",
      namuna: { stdin: ["5382"], out: ["18"] },
      tests: [["7"], ["100"], ["999"], ["10203"], ["1000000"], ["99999"]],
      solution: "n = int(input())\ns = 0\nwhile n > 0:\n    s += n % 10\n    n = n // 10\nprint(s)",
      hint: "n % 10 — oxirgi raqam, n // 10 — qolgani.",
    },
    {
      id: "teskari-son",
      rating: 350,
      tags: ["while", "raqamlar"],
      title: "Teskari son",
      what: "Bitta musbat son berilgan. Uni teskari oʻgirib chiqar.",
      kirish: "Bitta musbat butun son.",
      chiqish: "Bitta son.",
      namuna: { stdin: ["1234"], out: ["4321"] },
      tests: [["7"], ["100"], ["9081"], ["10"], ["120"], ["1000"], ["5"]],
      solution: "n = int(input())\nt = 0\nwhile n > 0:\n    t = t * 10 + n % 10\n    n = n // 10\nprint(t)",
      hint: "Har qadamda: t = t * 10 + oxirgi raqam.",
    },
    {
      id: "farq",
      rating: 350,
      tags: ["roʻyxat", "shart"],
      title: "Eng katta va eng kichik farqi",
      what: "Bitta satrda bir nechta son berilgan. Eng katta va eng kichik sonning farqini chiqar.",
      kirish: "Bitta satrda boʻsh joy bilan ajratilgan sonlar.",
      chiqish: "Bitta son.",
      namuna: { stdin: ["3 9 5"], out: ["6"] },
      tests: [["7"], ["10 2 8 4"], ["5 5 5"], ["-3 10 0"], ["-5 -5"], ["1 100"], ["-10 10 0"]],
      solution: "a = input().split()\nbest = int(a[0])\nworst = int(a[0])\nfor x in a:\n    v = int(x)\n    if v > best:\n        best = v\n    if v < worst:\n        worst = v\nprint(best - worst)",
      hint: "Ikkita quti kerak: eng katta va eng kichik.",
    },
    {
      id: "juftlar-soni",
      rating: 300,
      tags: ["roʻyxat", "shart"],
      title: "Nechta juft",
      what: "Bitta satrda bir nechta son berilgan. Nechtasi juft ekanini chiqar.",
      kirish: "Bitta satrda boʻsh joy bilan ajratilgan sonlar.",
      chiqish: "Bitta son.",
      namuna: { stdin: ["1 2 3 4"], out: ["2"] },
      tests: [["7"], ["2 4 6"], ["1 3 5"], ["0 1 2 3 4 5"], ["-2 -3 -4"], ["0"]],
      solution: "a = input().split()\nsoni = 0\nfor x in a:\n    if int(x) % 2 == 0:\n        soni += 1\nprint(soni)",
      hint: "split() dan keyin har boʻlakni int() bilan songa oʻgir.",
    },
    {
      id: "unlilar",
      rating: 300,
      tags: ["satr", "shart"],
      title: "Unli harflar",
      what: "Bitta soʻz berilgan. Undagi unli harflar (a, e, i, o, u) sonini chiqar.",
      kirish: "Bitta soʻz (kichik harflar bilan).",
      chiqish: "Bitta son.",
      namuna: { stdin: ["qabila"], out: ["3"] },
      tests: [["python"], ["aeiou"], ["kkk"], ["dastur"], ["qrst"], ["a"], ["uuuuuuuuuu"]],
      solution: 'soz = input()\nsoni = 0\nfor harf in soz:\n    if harf in "aeiou":\n        soni += 1\nprint(soni)',
      hint: "Unlilarni bitta satrga yozib qoʻy va har harf shu satrda bor-yoʻqligini tekshir.",
    },
    {
      id: "boluvchilar-soni",
      rating: 350,
      tags: ["for", "matematika"],
      title: "Boʻluvchilar soni",
      what: "Bitta musbat son berilgan. Uning nechta boʻluvchisi borligini chiqar.",
      kirish: "Bitta musbat butun son.",
      chiqish: "Bitta son.",
      namuna: { stdin: ["12"], out: ["6"] },
      tests: [["1"], ["7"], ["36"], ["100"], ["2"], ["97"], ["1000"]],
      solution: "n = int(input())\nsoni = 0\nfor i in range(1, n + 1):\n    if n % i == 0:\n        soni += 1\nprint(soni)",
      hint: "1 dan n gacha yurib, qoldiq nolga tengini sana.",
    },
    {
      id: "fibonachchi",
      rating: 450,
      tags: ["for", "oʻzgaruvchi"],
      title: "Fibonachchi",
      what: "Bitta son n berilgan. Fibonachchi ketma-ketligining n-hadini chiqar. Ketma-ketlik: 0, 1, 1, 2, 3, 5, … (1-had — 0).",
      kirish: "Bitta musbat butun son n.",
      chiqish: "Bitta son.",
      namuna: { stdin: ["7"], out: ["8"] },
      tests: [["1"], ["2"], ["10"], ["20"], ["3"], ["4"], ["30"]],
      solution: "n = int(input())\na = 0\nb = 1\nfor i in range(n - 1):\n    a, b = b, a + b\nprint(a)",
      hint: "Ikki qutini almashtirib bor: a, b = b, a + b.",
    },
    {
      id: "palindrom",
      rating: 400,
      tags: ["satr", "shart"],
      title: "Palindrom",
      what: 'Bitta soʻz berilgan. Agar u teskari oʻqilganda ham bir xil boʻlsa "ha", aks holda "yoʻq" deb yoz.',
      kirish: "Bitta soʻz.",
      chiqish: "ha yoki yoʻq.",
      namuna: { stdin: ["abba"], out: ["ha"] },
      tests: [["qabila"], ["a"], ["aba"], ["python"], ["ab"], ["aa"], ["abcba"], ["abcab"]],
      solution: 'soz = input()\nt = ""\nfor harf in soz:\n    t = harf + t\nif t == soz:\n    print("ha")\nelse:\n    print("yoʻq")',
      hint: "Avval soʻzni teskari yasab ol, keyin solishtir.",
    },
    {
      id: "qol-berish",
      rating: 400,
      tags: ["matematika", "kombinatorika"],
      title: "Qoʻl berib koʻrishish",
      what: "Xonada n kishi bor. Har ikkisi bir martadan qoʻl berib koʻrishdi. Nechta qoʻl berish boʻldi?",
      kirish: "Bitta butun son n (1 ≤ n ≤ 100000).",
      chiqish: "Bitta son — qoʻl berishlar soni.",
      namuna: { stdin: ["5"], out: ["10"] },
      tests: [["1"], ["2"], ["100"], ["100000"], ["3"], ["1000"]],
      solution: "n = int(input())\nprint(n * (n - 1) // 2)",
      hint: "Har kishi qolgan n−1 kishi bilan koʻrishadi, lekin har juftlik ikki marta sanaladi.",
    },
    {
      id: "jamoa-soni",
      rating: 500,
      tags: ["for", "kombinatorika"],
      title: "Jamoa tanlash",
      what: "n boladan k kishilik jamoa tuziladi. Jamoada tartib muhim emas. Nechta xil jamoa bor?",
      kirish: "Ikki satrda n va k (0 ≤ k ≤ n ≤ 30).",
      chiqish: "Bitta son — jamoalar soni.",
      namuna: { stdin: ["5", "3"], out: ["10"] },
      tests: [["6", "0"], ["7", "7"], ["10", "2"], ["30", "15"], ["0", "0"], ["30", "30"], ["30", "1"], ["20", "10"], ["8", "4"]],
      solution: "n = int(input())\nk = int(input())\nnatija = 1\nfor i in range(k):\n    natija = natija * (n - i)\nfor i in range(1, k + 1):\n    natija = natija // i\nprint(natija)",
      hint: "Avval n × (n−1) × … (k ta koʻpaytuvchi), keyin k! ga boʻl.",
    },
    {
      id: "kaptarxona",
      rating: 400,
      tags: ["matematika", "kombinatorika"],
      title: "Eng toʻla quti",
      what: "n ta xat k ta pochta qutisiga tashlandi. Qanday tashlanganidan qatʼi nazar, eng toʻla qutida kamida nechta xat bor?",
      kirish: "Ikki satrda n va k (1 ≤ n, k ≤ 1000000).",
      chiqish: "Bitta son — kafolatlangan eng kichik javob.",
      namuna: { stdin: ["13", "12"], out: ["2"] },
      tests: [["4", "4"], ["25", "12"], ["1", "1000"], ["1000000", "7"], ["1", "1"], ["12", "12"], ["13", "1"], ["1000000", "999999"], ["100", "7"]],
      solution: "n = int(input())\nk = int(input())\nprint((n + k - 1) // k)",
      hint: "Xatlarni qutilarga iloji boricha teng tashlasang, eng toʻlasida nechta boʻladi? Qoldiq boʻlsa-chi?",
    },
    {
      id: "harf-sanash",
      rating: 350,
      tags: ["satr", "for"],
      title: "Harf nechta?",
      what: "Soʻz va bitta harf berilgan. Shu harf soʻzda necha marta uchraydi?",
      kirish: "Birinchi satrda soʻz, ikkinchi satrda bitta harf.",
      chiqish: "Bitta son — harf necha marta uchragani.",
      namuna: { stdin: ["banana", "a"], out: ["3"] },
      tests: [["qabila", "a"], ["xxx", "y"], ["salom", "s"], ["aaaa", "a"], ["abcabc", "c"], ["z", "z"]],
      solution: "soz = input()\nharf = input()\nsoni = 0\nfor h in soz:\n    if h == harf:\n        soni += 1\nprint(soni)",
      hint: "Satr boʻylab yurish mumkin: for h in soz — h har safar bitta harf boʻladi.",
    },
  ];

  const QIYIN = [
    {
      id: "tubmi",
      rating: 550,
      tags: ["while", "matematika"],
      title: "Tub sonmi",
      what: 'Bitta son berilgan. Agar u tub son boʻlsa "ha", aks holda "yoʻq" deb yoz. (Tub son — 1 va oʻzidan boshqa boʻluvchisi yoʻq, 1 dan katta son.)',
      kirish: "Bitta butun son.",
      chiqish: "ha yoki yoʻq.",
      namuna: { stdin: ["13"], out: ["ha"] },
      tests: [["1"], ["2"], ["9"], ["97"], ["100"], ["0"], ["-5"], ["25"], ["49"], ["9973"], ["10007"], ["7919"]],
      solution: 'n = int(input())\ntub = True\nif n < 2:\n    tub = False\nd = 2\nwhile d * d <= n:\n    if n % d == 0:\n        tub = False\n    d += 1\nif tub:\n    print("ha")\nelse:\n    print("yoʻq")',
      hint: "Boʻluvchini n gacha qidirish shart emas — qayerda toʻxtasa boʻladi va nega? Chegaraning oʻzini ham tekshir (25, 49). 0, 1 va manfiy sonlar tub emas.",
    },
    {
      id: "tublar-soni",
      rating: 650,
      tags: ["for", "while", "matematika"],
      title: "Nechta tub son",
      what: "Bitta musbat son n berilgan. 2 dan n gacha (n ham kiradi) nechta tub son borligini chiqar.",
      kirish: "Bitta musbat butun son.",
      chiqish: "Bitta son.",
      namuna: { stdin: ["10"], out: ["4"] },
      tests: [["1"], ["2"], ["20"], ["50"], ["3"], ["100"], ["997"]],
      solution: "n = int(input())\nsoni = 0\nfor x in range(2, n + 1):\n    tub = True\n    d = 2\n    while d * d <= x:\n        if x % d == 0:\n            tub = False\n        d += 1\n    if tub:\n        soni += 1\nprint(soni)",
      hint: "Har bir sonni alohida tekshir — ichma-ich sikl kerak boʻladi.",
    },
    {
      id: "ekub",
      rating: 600,
      tags: ["while", "matematika"],
      title: "Eng katta umumiy boʻluvchi",
      what: "Ikkita musbat son berilgan. Ularning eng katta umumiy boʻluvchisini chiqar.",
      kirish: "Ikki satrda ikkita musbat son.",
      chiqish: "Bitta son.",
      namuna: { stdin: ["12", "18"], out: ["6"] },
      tests: [["7", "13"], ["100", "75"], ["5", "5"], ["36", "12"], ["1", "1"], ["1", "100"], ["1000000", "1"], ["17", "289"], ["1000000", "999999"]],
      solution: "a = int(input())\nb = int(input())\nwhile b > 0:\n    r = a % b\n    a = b\n    b = r\nprint(a)",
      hint: "Ikki sonning umumiy boʻluvchisi ularning farqini ham boʻladi. Shundan foydalanib sonlarni kichraytirib bor — birma-bir sinab chiqish katta sonlarda juda uzoq.",
    },
    {
      id: "ikkinchi-katta",
      rating: 500,
      tags: ["roʻyxat", "saralash"],
      title: "Ikkinchi eng katta",
      what: "Bitta satrda bir nechta har xil son berilgan. Ikkinchi eng kattasini chiqar.",
      kirish: "Bitta satrda kamida ikkita har xil son.",
      chiqish: "Bitta son.",
      namuna: { stdin: ["3 9 5"], out: ["5"] },
      tests: [["10 2"], ["1 7 4 9 2"], ["100 50 75"], ["-3 -1 -7"], ["1 2 3 4 5 6 7 8 9 10"], ["-100 100"]],
      solution: "a = input().split()\nb = []\nfor x in a:\n    b.append(int(x))\nb = sorted(b)\nprint(b[len(b) - 2])",
      hint: "Saralangan roʻyxatda oxiridan ikkinchisi kerak.",
    },
    {
      id: "ikkilik",
      rating: 600,
      tags: ["while", "satr", "raqamlar"],
      title: "Ikkilik yozuv",
      what: "Bitta musbat son berilgan. Uni ikkilik sanoq tizimida chiqar.",
      kirish: "Bitta musbat butun son.",
      chiqish: "Nol va birlardan iborat satr.",
      namuna: { stdin: ["10"], out: ["1010"] },
      tests: [["1"], ["2"], ["255"], ["64"], ["3"], ["1023"], ["1024"]],
      solution: 'n = int(input())\ns = ""\nwhile n > 0:\n    s = str(n % 2) + s\n    n = n // 2\nprint(s)',
      hint: "Har qadamda 2 ga boʻlib, qoldiqni oldinga qoʻshib bor.",
    },
    {
      id: "faktorial",
      rating: 300,
      tags: ["for", "matematika", "kombinatorika"],
      title: "Faktorial",
      what: "Bitta musbat son n berilgan. n! ni chiqar (1 dan n gacha sonlar koʻpaytmasi).",
      kirish: "Bitta musbat butun son n (1 ≤ n ≤ 20).",
      chiqish: "Bitta son.",
      namuna: { stdin: ["5"], out: ["120"] },
      tests: [["1"], ["3"], ["10"], ["20"], ["2"], ["15"]],
      solution: "n = int(input())\ns = 1\nfor i in range(1, n + 1):\n    s = s * i\nprint(s)",
      hint: "Yigʻindidagidek, faqat s = 1 dan boshlanadi va koʻpaytiriladi.",
    },
    {
      id: "har-xil",
      rating: 650,
      tags: ["roʻyxat", "saralash"],
      title: "Nechta har xil son",
      what: "Bitta satrda bir nechta son berilgan. Ular orasida nechta har xil son borligini chiqar.",
      kirish: "Bitta satrda boʻsh joy bilan ajratilgan sonlar.",
      chiqish: "Bitta son.",
      namuna: { stdin: ["1 2 2 3 1"], out: ["3"] },
      tests: [["5"], ["7 7 7"], ["1 2 3 4"], ["10 2 10 2 5"], ["-1 1 -1"], ["0"], ["5 4 3 2 1"]],
      solution: "a = input().split()\nb = []\nfor x in a:\n    b.append(int(x))\nb = sorted(b)\nsoni = 0\nfor i in range(len(b)):\n    if i == 0:\n        soni += 1\n    elif b[i] != b[i - 1]:\n        soni += 1\nprint(soni)",
      hint: "Saralasang, bir xil sonlar yonma-yon turadi.",
    },
    {
      id: "boluvchilar",
      rating: 300,
      tags: ["for", "matematika"],
      title: "Boʻluvchilarni chiqar",
      what: "Bitta musbat son berilgan. Uning barcha boʻluvchilarini oʻsish tartibida, har satrda bittadan chiqar.",
      kirish: "Bitta musbat butun son.",
      chiqish: "Har satrda bitta boʻluvchi.",
      namuna: { stdin: ["12"], out: ["1", "2", "3", "4", "6", "12"] },
      tests: [["1"], ["7"], ["16"], ["30"], ["2"], ["36"]],
      solution: "n = int(input())\nfor i in range(1, n + 1):\n    if n % i == 0:\n        print(i)",
      hint: "1 dan n gacha yurib, qoldiq nolga teng boʻlsa chiqar.",
    },
    {
      id: "paskal-qator",
      rating: 600,
      tags: ["roʻyxat", "kombinatorika"],
      title: "Paskal qatori",
      what: "Paskal uchburchagining n-qatorini chiqar. Sonlar bitta satrda, boʻsh joy bilan ajratilgan. 0-qator — bitta 1.",
      kirish: "Bitta butun son n (0 ≤ n ≤ 30).",
      chiqish: "n-qator sonlari bitta satrda.",
      namuna: { stdin: ["5"], out: ["1 5 10 10 5 1"] },
      tests: [["0"], ["1"], ["10"], ["30"], ["2"], ["29"]],
      solution: "n = int(input())\na = [1]\nfor i in range(n):\n    yangi = [1]\n    for j in range(len(a) - 1):\n        yangi.append(a[j] + a[j + 1])\n    yangi.append(1)\n    a = yangi\njavob = str(a[0])\nfor i in range(1, len(a)):\n    javob = javob + \" \" + str(a[i])\nprint(javob)",
      hint: "Har qator chekkalari 1, ichkarisi — oldingi qatordagi qoʻshni ikkitaning yigʻindisi.",
    },
    {
      id: "parol-soni",
      rating: 500,
      tags: ["for", "kombinatorika"],
      title: "Nechta parol bor",
      what: "Alifboda a ta belgi bor. Uzunligi 1 dan n gacha boʻlgan nechta parol yasash mumkin? (Belgilar takrorlanishi mumkin.)",
      kirish: "Ikki satrda a va n (1 ≤ a ≤ 100, 1 ≤ n ≤ 10).",
      chiqish: "Bitta son — parollar soni.",
      namuna: { stdin: ["2", "3"], out: ["14"] },
      tests: [["1", "5"], ["10", "1"], ["26", "4"], ["100", "10"], ["1", "1"], ["2", "1"], ["100", "1"]],
      solution: "a = int(input())\nn = int(input())\njami = 0\ndaraja = 1\nfor i in range(n):\n    daraja = daraja * a\n    jami = jami + daraja\nprint(jami)",
      hint: "Uzunligi i boʻlgan parollar soni — a ning i-darajasi. Hammasini qoʻshish kerak (qoʻshish qoidasi).",
    },
    {
      id: "tanga-gerb",
      rating: 700,
      tags: ["for", "kombinatorika"],
      title: "Tanga va gerb",
      what: "Tanga n marta tashlandi. Har tashlashda gerb yoki raqam tushadi. Kamida k martasida gerb tushadigan nechta xil natija bor? (Natija — qaysi tashlashda nima tushgani; tartib muhim.)",
      kirish: "Ikki satrda n va k (0 ≤ k ≤ n ≤ 30).",
      chiqish: "Bitta son — natijalar soni.",
      namuna: { stdin: ["4", "2"], out: ["11"] },
      tests: [["1", "0"], ["5", "5"], ["10", "3"], ["30", "15"], ["0", "0"], ["30", "0"], ["3", "1"], ["6", "4"]],
      solution: "n = int(input())\nk = int(input())\njami = 0\nfor i in range(k, n + 1):\n    c = 1\n    for j in range(i):\n        c = c * (n - j)\n    for j in range(1, i + 1):\n        c = c // j\n    jami += c\nprint(jami)",
      hint: "«Kamida k» — bir nechta holatning yigʻindisi: aynan k marta, aynan k + 1 marta, … aynan n marta. Har holatni alohida sana (jamoa tanlashdagidek) va qoʻsh.",
    },
    {
      id: "izlash-joy",
      rating: 500,
      tags: ["izlash", "for"],
      title: "Nechanchi oʻrinda",
      what: "n ta son va x berilgan. x roʻyxatda nechanchi oʻrinda turibdi (1 dan sanaladi)? Bir necha marta uchrasa — birinchisini chiqar, topilmasa −1.",
      kirish: "Birinchi satrda n, ikkinchida n ta son, uchinchida x.",
      chiqish: "Oʻrin raqami yoki −1.",
      namuna: { stdin: ["5", "3 9 1 7 5", "7"], out: ["4"] },
      tests: [["3", "1 2 3", "9"], ["4", "5 5 5 5", "5"], ["5", "3 9 1 7 5", "3"], ["1", "8", "8"], ["5", "1 2 3 4 9", "9"], ["3", "7 7 7", "7"], ["2", "5 6", "6"], ["6", "4 8 15 16 23 42", "16"], ["4", "7 7 3 7", "3"]],
      solution: "n = int(input())\na = []\nfor s in input().split():\n    a.append(int(s))\nx = int(input())\njoy = -1\nfor i in range(n):\n    if a[i] == x and joy == -1:\n        joy = i + 1\nprint(joy)",
      hint: "Chiziqli izlash: birinchisidan boshlab birma-bir qara. Topgach, keyingilari javobni oʻzgartirmasin.",
    },
    {
      id: "ikkilik-izlash",
      rating: 700,
      tags: ["izlash", "while"],
      title: "Ikkilik izlash",
      what: "Oʻsish tartibida tartiblangan n ta son va x berilgan. x ni ikkilik izlash bilan qidir va qaysi oʻrinlarga qaraganingni koʻrsat. Qoida: chap = 1, oʻng = n. Har qadamda oʻrta = (chap + oʻng) // 2 va oʻrta oʻrindagi son x bilan solishtiriladi: teng boʻlsa — topildi, toʻxta; x dan kichik boʻlsa — chap = oʻrta + 1; katta boʻlsa — oʻng = oʻrta − 1. chap oʻngdan oshib ketsa — x roʻyxatda yoʻq.",
      kirish: "Birinchi satrda n (1 ≤ n ≤ 1000), ikkinchida n ta tartiblangan son, uchinchida x.",
      chiqish: "Birinchi satrda qaralgan oʻrta oʻrinlar (1 dan sanaladi) tartib bilan, boʻsh joy bilan ajratilgan. Ikkinchi satrda bor yoki yoʻq.",
      namuna: { stdin: ["5", "1 3 5 7 9", "7"], out: ["3 4", "bor"] },
      tests: [
        ["5", "1 3 5 7 9", "4"], ["1", "42", "42"], ["6", "2 4 6 8 10 12", "2"], ["6", "2 4 6 8 10 12", "13"],
        ["5", "1 3 5 7 9", "0"], ["5", "1 3 5 7 9", "10"], ["5", "1 3 5 7 9", "9"], ["2", "1 2", "2"], ["8", "1 2 3 4 5 6 7 8", "1"],
      ],
      solution: "n = int(input())\na = []\nfor s in input().split():\n    a.append(int(s))\nx = int(input())\nchap = 1\nong = n\ntopildi = False\nqaralgan = \"\"\nwhile chap <= ong and not topildi:\n    orta = (chap + ong) // 2\n    if qaralgan == \"\":\n        qaralgan = str(orta)\n    else:\n        qaralgan = qaralgan + \" \" + str(orta)\n    if a[orta - 1] == x:\n        topildi = True\n    elif a[orta - 1] < x:\n        chap = orta + 1\n    else:\n        ong = orta - 1\nprint(qaralgan)\nif topildi:\n    print(\"bor\")\nelse:\n    print(\"yoʻq\")",
      hint: "Har qadamda oʻrta oʻrinni javob satriga qoʻshib bor. Roʻyxat 0 dan indekslanadi: oʻrta oʻrindagi son — a[oʻrta − 1]. Topilgan zahoti toʻxta — ortiqcha oʻrin chiqmasin.",
    },
    {
      id: "k-kichik",
      rating: 600,
      tags: ["saralash", "roʻyxat"],
      title: "k-eng kichik har xil son",
      what: "n ta son berilgan, ular takrorlanishi mumkin. Har xil sonlarni oʻsish tartibida yozsak, k-oʻrinda qaysi son turadi? Takrorlangan son bir marta hisoblanadi: «4 4 2 2 2» da har xil sonlar faqat ikkita — 2 va 4. Har xil sonlar k tadan kam boʻlsa, −1 chiqar.",
      kirish: "Birinchi satrda n, ikkinchida n ta butun son, uchinchida k (1 ≤ k ≤ n).",
      chiqish: "Bitta son yoki −1.",
      namuna: { stdin: ["6", "5 3 5 1 3 9", "3"], out: ["5"] },
      tests: [
        ["3", "10 20 30", "3"], ["4", "4 4 2 2", "1"], ["5", "5 4 3 2 1", "5"], ["1", "7", "1"],
        ["5", "4 4 2 2 2", "3"], ["3", "-1 -5 -3", "1"], ["7", "1 1 1 1 1 1 1", "2"], ["6", "2 1 2 1 3 3", "3"], ["8", "0 -1 0 -1 5 5 5 7", "4"],
      ],
      solution: "n = int(input())\na = []\nfor s in input().split():\n    a.append(int(s))\nk = int(input())\nb = sorted(a)\nharxil = []\nfor i in range(len(b)):\n    if i == 0 or b[i] != b[i - 1]:\n        harxil.append(b[i])\nif k <= len(harxil):\n    print(harxil[k - 1])\nelse:\n    print(-1)",
      hint: "Saralasang, bir xil sonlar yonma-yon turadi. Oldingisidan farq qiladiganlarini yangi roʻyxatga yigʻ — k shu roʻyxat uzunligidan oshib ketishi ham mumkin.",
    },
    {
      id: "ortachadan-katta",
      rating: 550,
      tags: ["roʻyxat", "matematika"],
      title: "Oʻrtachadan katta",
      what: "n ta son berilgan. Nechtasi oʻrtacha qiymatdan katta?",
      kirish: "Birinchi satrda n, ikkinchida n ta son.",
      chiqish: "Bitta son.",
      namuna: { stdin: ["5", "1 2 3 4 5"], out: ["2"] },
      tests: [["3", "7 7 7"], ["4", "1 1 1 100"], ["6", "1 2 3 4 5 6"], ["2", "0 10"], ["1", "5"], ["3", "-1 -2 -3"], ["4", "1 1 1 2"]],
      solution: "n = int(input())\na = []\nfor s in input().split():\n    a.append(int(s))\njami = 0\nfor x in a:\n    jami += x\nsoni = 0\nfor x in a:\n    if x * n > jami:\n        soni += 1\nprint(soni)",
      hint: "Kasrdan qochish uchun x > jami/n oʻrniga x * n > jami deb solishtir.",
    },
  ];


  // Teglar — bizning mavzularimiz: masala qaysi darslarga tayanadi
  const TAGS = ["oʻzgaruvchi", "matematika", "shart", "while", "for", "roʻyxat", "satr", "raqamlar", "saralash", "funksiya", "kombinatorika", "izlash"];

  // Katta testlar: samarasiz (O(n·q) yoki O(n²)) yechimni masalaning `qadam` chegarasiga urdiradi.
  const ketma = (n, f) => Array.from({ length: n }, (_, i) => f(i + 1)).join(" ");
  // cf-qurtlar: 1000 uyum (1–13 tadan olma), 200 savol — hammasi qatorning ikkinchi yarmidan
  const KATTA_QURTLAR = (() => {
    const uyum = Array.from({ length: 1000 }, (_, i) => 1 + (((i + 1) * 7919) % 13));
    const jami = uyum.reduce((a, b) => a + b, 0);
    return ["1000", uyum.join(" "), "200", ketma(200, (j) => jami - ((j * 7919) % Math.floor(jami / 2)))];
  })();

  // Codeforces'dan olingan masalalar. SHARTLAR OʻZIMIZNIKI — asl matn koʻchirilmagan,
  // faqat masalaning gʻoyasi olingan va manbaga havola qoʻyilgan (mualliflik huquqi).
  // rating va cfTags — Codeforces API dan olingan haqiqiy qiymatlar (2026-09-30; 2026-10-02 da qayta solishtirildi:
  // 474B — 1200; 1A bizda 900, chunki CF dagi 64-bit tuzogʻi Pythonda yoʻq).
  const CF = [
    {
      id: "cf-tarvuz",
      tartib: 1,
      title: "Tarvuzni boʻlish",
      what: "Tarvuzning ogʻirligi w kilogramm. Uni ikkita boʻlakka boʻlmoqchimiz, har bir boʻlakning ogʻirligi juft son va noldan katta boʻlsin. Shunday boʻlish mumkinmi?",
      kirish: "Bitta butun son w (1 ≤ w ≤ 100).",
      chiqish: 'Mumkin boʻlsa "ha", aks holda "yoʻq".',
      namuna: { stdin: ["8"], out: ["ha"] },
      tests: [["2"], ["1"], ["100"], ["3"], ["4"], ["99"], ["98"]],
      solution: 'w = int(input())\nif w % 2 == 0 and w > 2:\n    print("ha")\nelse:\n    print("yoʻq")',
      hint: "Juft sonni ikki juft boʻlakka boʻlish mumkin — lekin 2 ni boʻlib boʻlmaydi (0 boʻlak chiqadi).",
      rating: 800,
      tags: ["shart", "matematika"],
      manba: { kod: "4A", nom: "Watermelon", cfTags: ["brute force", "math"], url: "https://codeforces.com/problemset/problem/4/A" },
      animatsiya: null,
    },
    {
      id: "cf-domino",
      tartib: 2,
      title: "Nechta domino sigʻadi",
      what: "Oʻlchami m × n boʻlgan toʻrtburchak taxta bor. Unga oʻlchami 1 × 2 boʻlgan dominolarni bir-birining ustiga chiqmasdan, taxtadan tashqariga chiqmasdan joylaymiz. Eng koʻpi bilan nechta domino sigʻadi?",
      kirish: "Bitta satrda ikkita son: m va n (1 ≤ m, n ≤ 16).",
      chiqish: "Bitta son — dominolar soni.",
      namuna: { stdin: ["2 4"], out: ["4"] },
      tests: [["1 1"], ["3 3"], ["16 16"], ["1 5"], ["5 1"], ["16 15"], ["1 16"]],
      solution: "s = input().split()\nm = int(s[0])\nn = int(s[1])\nprint(m * n // 2)",
      hint: "Har domino 2 katakni egallaydi. Kataklar soni toq boʻlsa, bittasi boʻsh qoladi.",
      rating: 800,
      tags: ["matematika"],
      manba: { kod: "50A", nom: "Domino piling", cfTags: ["greedy", "math"], url: "https://codeforces.com/problemset/problem/50/A" },
      animatsiya: null,
    },
    {
      id: "cf-fil",
      tartib: 3,
      title: "Filning qadamlari",
      what: "Fil sonlar oʻqining 0 nuqtasida turibdi. Uning doʻsti x nuqtada. Fil bir qadamda 1, 2, 3, 4 yoki 5 pogʻona oʻngga yura oladi. Doʻstiga yetib borish uchun unga eng kamida nechta qadam kerak?",
      kirish: "Bitta butun son x (1 ≤ x ≤ 1 000 000).",
      chiqish: "Bitta son — qadamlar soni.",
      namuna: { stdin: ["12"], out: ["3"] },
      tests: [["5"], ["1"], ["6"], ["1000000"], ["10"], ["4"], ["11"], ["999999"]],
      solution: "x = int(input())\nprint((x + 4) // 5)",
      hint: "Eng tez yoʻl — 5 pogʻonadan yurish. Oxirida qolgan masofa uchun yana bitta qadam kerak boʻlishi mumkin.",
      rating: 800,
      tags: ["matematika"],
      manba: { kod: "617A", nom: "Elephant", cfTags: ["math"], url: "https://codeforces.com/problemset/problem/617/A" },
      animatsiya: null,
    },
    {
      id: "cf-ukalar",
      tartib: 4,
      title: "Ukam qachon oʻzib ketadi",
      what: "Kichik ukaning vazni a, kattasiniki b (a ≤ b). Har yili kichigining vazni 3 baravar, kattasiniki 2 baravar oshadi. Kichigining vazni kattasinikidan qatʼiy koʻp boʻlishi uchun necha yil kerak?",
      kirish: "Bitta satrda ikkita son: a va b (1 ≤ a ≤ b ≤ 10).",
      chiqish: "Bitta son — yillar soni.",
      namuna: { stdin: ["4 7"], out: ["2"] },
      tests: [["1 1"], ["10 10"], ["1 10"], ["4 9"], ["2 3"], ["1 2"], ["9 10"], ["5 5"]],
      solution: "s = input().split()\na = int(s[0])\nb = int(s[1])\nyil = 0\nwhile a <= b:\n    a = a * 3\n    b = b * 2\n    yil += 1\nprint(yil)",
      hint: "Sikl a > b boʻlguncha davom etadi. Har aylanishda ikkala vaznni ham yangila.",
      rating: 800,
      tags: ["while", "oʻzgaruvchi"],
      manba: { kod: "791A", nom: "Bear and Big Brother", cfTags: ["implementation"], url: "https://codeforces.com/problemset/problem/791/A" },
      animatsiya: null,
    },
    {
      id: "cf-notogri-ayirish",
      tartib: 5,
      title: "Notoʻgʻri ayirish",
      what: "Tanya sonni bittaga kamaytirishni bilmaydi. U shunday qiladi: agar sonning oxirgi raqami 0 boʻlsa, oxirgi raqamni oʻchiradi; aks holda sondan 1 ayiradi. Tanya shu amalni k marta bajarsa, qanday son qoladi?",
      kirish: "Bitta satrda ikkita son: n va k (2 ≤ n ≤ 10⁹, 1 ≤ k ≤ 50). Natija doim musbat boʻladi.",
      chiqish: "Bitta son.",
      namuna: { stdin: ["512 4"], out: ["50"] },
      tests: [["1000000000 9"], ["100 1"], ["2 1"], ["10 1"], ["999 3"], ["100 2"], ["11 1"]],
      solution: "s = input().split()\nn = int(s[0])\nk = int(s[1])\nfor i in range(k):\n    if n % 10 == 0:\n        n = n // 10\n    else:\n        n = n - 1\nprint(n)",
      hint: "Oxirgi raqamni n % 10 beradi, oʻchirishni n // 10 qiladi.",
      rating: 800,
      tags: ["for", "raqamlar", "shart"],
      manba: { kod: "977A", nom: "Wrong Subtraction", cfTags: ["implementation"], url: "https://codeforces.com/problemset/problem/977/A" },
      animatsiya: null,
    },
    {
      id: "cf-jamoa",
      tartib: 8,
      title: "Jamoa qaroriga koʻra",
      what: "Uch doʻst olimpiadada qatnashmoqda. Har masala uchun har biri oʻzining ishonchini bildiradi: 1 — yechimni bilaman, 0 — bilmayman. Agar kamida ikkitasi ishonsa, jamoa shu masalani yozishga kirishadi. Nechta masalani yozishadi?",
      kirish: "Birinchi satrda n (1 ≤ n ≤ 1000) — masalalar soni. Keyingi n satrda uchtadan 0 yoki 1.",
      chiqish: "Bitta son — yoziladigan masalalar soni.",
      namuna: { stdin: ["3", "1 1 0", "1 1 1", "1 0 0"], out: ["2"] },
      tests: [["1", "0 0 0"], ["1", "1 1 1"], ["2", "1 0 1", "0 1 1"], ["4", "0 0 0", "1 1 0", "0 1 1", "1 0 0"], ["3", "1 1 0", "0 1 1", "1 0 1"], ["2", "0 0 1", "1 0 0"]],
      solution: "n = int(input())\nsoni = 0\nfor i in range(n):\n    s = input().split()\n    yigindi = int(s[0]) + int(s[1]) + int(s[2])\n    if yigindi >= 2:\n        soni += 1\nprint(soni)",
      hint: "Har satrni alohida input() bilan oʻqi. Uch sonning yigʻindisi 2 dan kam boʻlmasa — sanaysan.",
      rating: 800,
      tags: ["for", "shart", "roʻyxat"],
      manba: { kod: "231A", nom: "Team", cfTags: ["brute force", "greedy"], url: "https://codeforces.com/problemset/problem/231/A" },
      animatsiya: null,
    },
    {
      id: "cf-toshlar",
      tartib: 6,
      title: "Stol ustidagi toshlar",
      what: "Stolda bir qator tosh turibdi, har biri qizil (R), yashil (G) yoki koʻk (B). Yonma-yon turgan ikki tosh bir xil rangda boʻlmasligi kerak. Shu shart bajarilishi uchun eng kamida nechta toshni olib tashlash kerak?",
      kirish: "Birinchi satrda n (1 ≤ n ≤ 50). Ikkinchi satrda n ta harfdan iborat satr: faqat R, G va B.",
      chiqish: "Bitta son — olib tashlanadigan toshlar soni.",
      namuna: { stdin: ["3", "RRG"], out: ["1"] },
      tests: [["1", "R"], ["5", "RGBGR"], ["4", "RRRR"], ["6", "BBGGRR"], ["2", "RG"], ["3", "RGB"], ["7", "RRRRRRR"], ["5", "RRGGB"], ["8", "RGGGBBRR"]],
      solution: "n = int(input())\ns = input()\nsoni = 0\nfor i in range(1, len(s)):\n    if s[i] == s[i - 1]:\n        soni += 1\nprint(soni)",
      hint: "Har harfni oʻzidan oldingisi bilan solishtir. Birinchi harfning oldingisi yoʻq — shuning uchun sikl 1 dan boshlanadi.",
      rating: 800,
      tags: ["satr", "for", "shart"],
      manba: { kod: "266A", nom: "Stones on the Table", cfTags: ["implementation"], url: "https://codeforces.com/problemset/problem/266/A" },
      animatsiya: null,
    },
    {
      id: "cf-hisoblagich",
      tartib: 7,
      title: "Gʻalati hisoblagich",
      what: "Boshida x = 0. Sizga n ta buyruq beriladi, har biri x ni bittaga oshiradi yoki bittaga kamaytiradi. Buyruq uch belgidan iborat: ichida ++ boʻlsa — oshirish, -- boʻlsa — kamaytirish (masalan ++x, x++, --x, x--). Oxirida x qanday boʻladi?",
      kirish: "Birinchi satrda n (1 ≤ n ≤ 150). Keyingi n satrda bittadan buyruq.",
      chiqish: "Bitta son — oxirgi x.",
      namuna: { stdin: ["2", "++x", "--x"], out: ["0"] },
      tests: [["1", "x++"], ["1", "x--"], ["3", "++x", "++x", "x++"], ["4", "--x", "x--", "++x", "x++"], ["2", "x++", "++x"], ["3", "x--", "--x", "x--"]],
      solution: 'n = int(input())\nx = 0\nfor i in range(n):\n    buyruq = input()\n    if "+" in buyruq:\n        x += 1\n    else:\n        x -= 1\nprint(x)',
      hint: 'Butun buyruqni tekshirish shart emas: "+" in buyruq — ichida plus bormi degani.',
      rating: 800,
      tags: ["for", "satr", "shart"],
      manba: { kod: "282A", nom: "Bit++", cfTags: ["implementation"], url: "https://codeforces.com/problemset/problem/282/A" },
      animatsiya: null,
    },
    {
      id: "cf-satr-solishtirish",
      tartib: 9,
      title: "Ikki soʻzni solishtirish",
      what: "Ikkita bir xil uzunlikdagi soʻz berilgan. Ularni katta-kichik harf farqiga eʼtibor bermay solishtiring: birinchisi alifboda oldin kelsa −1, keyin kelsa 1, teng boʻlsa 0 chiqaring.",
      kirish: "Ikki satrda ikkita soʻz (uzunligi 100 dan oshmaydi, faqat lotin harflari).",
      chiqish: "−1, 0 yoki 1.",
      namuna: { stdin: ["aaaa", "aaaA"], out: ["0"] },
      tests: [["abs", "Abz"], ["abcdefg", "AbCdEfF"], ["a", "b"], ["zz", "ZZ"], ["Ba", "ab"], ["a", "B"], ["abc", "ABC"], ["Zz", "zA"]],
      solution: "a = input().lower()\nb = input().lower()\nif a < b:\n    print(-1)\nelif a > b:\n    print(1)\nelse:\n    print(0)",
      hint: "Avval ikkala soʻzni kichik harfga oʻgir (lower), keyin oddiy solishtirish belgilari bilan solishtir.",
      rating: 800,
      tags: ["satr", "shart"],
      manba: { kod: "112A", nom: "Petya and Strings", cfTags: ["implementation", "strings"], url: "https://codeforces.com/problemset/problem/112/A" },
      animatsiya: null,
    },
    {
      id: "cf-har-xil-harf",
      tartib: 10,
      title: "Ismdagi har xil harflar",
      what: 'Bitta soʻz berilgan. Undagi har xil harflar sonini toping: agar bu son juft boʻlsa "juft", aks holda "toq" deb yozing.',
      kirish: "Bitta soʻz (uzunligi 100 dan oshmaydi, kichik lotin harflari).",
      chiqish: "juft yoki toq.",
      namuna: { stdin: ["bananas"], out: ["juft"] },
      tests: [["a"], ["ab"], ["aabbcc"], ["qabila"], ["xxxxx"], ["abcdefghijklmnopqrstuvwxyz"], ["zzzzzzzzzzzzzzzzzzzzzzzza"]],
      solution: 'soz = input()\nb = sorted(soz)\nsoni = 0\nfor i in range(len(b)):\n    if i == 0:\n        soni += 1\n    elif b[i] != b[i - 1]:\n        soni += 1\nif soni % 2 == 0:\n    print("juft")\nelse:\n    print("toq")',
      hint: "Harflarni saralasang, bir xillari yonma-yon turadi — shunda har xillarini sanash oson.",
      rating: 800,
      tags: ["satr", "saralash", "for"],
      manba: { kod: "236A", nom: "Boy or Girl", cfTags: ["brute force", "implementation", "strings"], url: "https://codeforces.com/problemset/problem/236/A" },
      animatsiya: null,
    },
    {
      id: "cf-eng-uzun-osish",
      tartib: 11,
      title: "Eng uzun kunlar",
      what: "Bola n kun davomida masala yechdi. Har kuni nechta yechgani maʼlum. Eng uzun ketma-ket kunlar qatorini toping: unda har kuni oldingi kundan kam yechilmagan boʻlsin.",
      kirish: "Birinchi satrda n (1 ≤ n ≤ 1000), ikkinchida n ta son.",
      chiqish: "Bitta son — eng uzun qatordagi kunlar soni.",
      namuna: { stdin: ["6", "2 2 1 3 4 1"], out: ["3"] },
      tests: [["3", "2 2 9"], ["5", "5 4 3 2 1"], ["1", "7"], ["7", "1 2 3 1 2 3 4"], ["3", "3 3 3"], ["4", "4 3 2 1"], ["5", "1 2 1 2 3"]],
      solution: "n = int(input())\na = []\nfor s in input().split():\n    a.append(int(s))\nbest = 1\nhozir = 1\nfor i in range(1, n):\n    if a[i] >= a[i - 1]:\n        hozir += 1\n    else:\n        hozir = 1\n    if hozir > best:\n        best = hozir\nprint(best)",
      hint: "Bitta oʻtishda yetadi: hozirgi qator uzunligini saqlab bor, kamaysa — 1 dan boshla.",
      rating: 900,
      tags: ["roʻyxat", "for"],
      manba: { kod: "580A", nom: "Kefa and First Steps", cfTags: ["brute force", "dp", "implementation"], url: "https://codeforces.com/problemset/problem/580/A" },
      animatsiya: null,
    },
    {
      id: "cf-maydon",
      tartib: 12,
      title: "Maydonga plitka",
      what: "Toʻrtburchak maydon n × m metr. Uni a × a metrli kvadrat plitkalar bilan toʻliq yopmoqchimiz. Plitkalarni sindirib boʻlmaydi, lekin maydondan chetga chiqsa — mayli. Eng kamida nechta plitka kerak?",
      kirish: "Uch satrda n, m va a (1 ≤ n, m, a ≤ 1000000000).",
      chiqish: "Bitta son — plitkalar soni.",
      namuna: { stdin: ["6", "6", "4"], out: ["4"] },
      tests: [["1", "1", "1"], ["1000000000", "1000000000", "1"], ["7", "5", "3"], ["2", "9", "4"], ["4", "4", "4"], ["1", "1", "1000000000"], ["5", "7", "2"]],
      solution: "n = int(input())\nm = int(input())\na = int(input())\nprint(((n + a - 1) // a) * ((m + a - 1) // a))",
      hint: "Har tomon uchun boʻlishni yuqoriga yumalatish kerak: (n + a − 1) // a. Javob juda katta boʻlishi mumkin.",
      rating: 900,
      tags: ["matematika"],
      manba: { kod: "1A", nom: "Theatre Square", cfTags: ["math"], url: "https://codeforces.com/problemset/problem/1/A" },
      animatsiya: null,
    },
    {
      id: "cf-aylana-yol",
      tartib: 13,
      title: "Aylana koʻcha",
      what: "n ta uy aylana boʻylab joylashgan: 1-dan 2-ga, 2-dan 3-ga … n-dan yana 1-ga faqat soat yoʻnalishida yurish mumkin. Har qadam 1 daqiqa. Kuryer 1-uydan boshlaydi va vazifalarni berilgan tartibda bajaradi. Jami necha daqiqa ketadi?",
      kirish: "Birinchi satrda n va ikkinchida m (vazifalar soni, 1 ≤ m ≤ 1000), uchinchida m ta uy raqami.",
      chiqish: "Bitta son — jami daqiqa.",
      namuna: { stdin: ["4", "3", "3 2 3"], out: ["6"] },
      tests: [["4", "3", "2 3 3"], ["5", "1", "1"], ["10", "4", "10 1 10 1"], ["3", "3", "3 3 3"], ["4", "2", "1 1"], ["5", "2", "5 4"], ["2", "3", "2 1 2"]],
      solution: "n = int(input())\nm = int(input())\nvazifa = []\nfor s in input().split():\n    vazifa.append(int(s))\nvaqt = 0\nhozir = 1\nfor v in vazifa:\n    if v >= hozir:\n        vaqt += v - hozir\n    else:\n        vaqt += n - hozir + v\n    hozir = v\nprint(vaqt)",
      hint: "Agar keyingi uy oldinda boʻlsa — ayirma; orqada boʻlsa, aylanani toʻliq aylanib chiqish kerak.",
      rating: 1000,
      tags: ["roʻyxat", "shart"],
      manba: { kod: "339B", nom: "Xenia and Ringroad", cfTags: ["implementation", "math"], url: "https://codeforces.com/problemset/problem/339/B" },
      animatsiya: null,
    },
    {
      id: "cf-taksi",
      tartib: 14,
      title: "Nechta taksi",
      what: "Bogʻchaning n ta guruhi ekskursiyaga boradi. Har guruhda 1 dan 4 gacha bola bor va guruhni boʻlish mumkin emas. Bitta taksiga 4 tagacha bola sigʻadi. Eng kamida nechta taksi kerak?",
      kirish: "Birinchi satrda n (1 ≤ n ≤ 1000), ikkinchida n ta son (har biri 1–4).",
      chiqish: "Bitta son — taksilar soni.",
      namuna: { stdin: ["5", "1 2 4 3 3"], out: ["4"] },
      tests: [["8", "2 3 4 4 2 1 3 1"], ["1", "1"], ["4", "2 2 2 2"], ["6", "1 1 1 1 1 1"], ["1", "3"], ["2", "3 1"], ["3", "3 3 3"], ["5", "2 2 2 1 1"], ["3", "1 1 2"]],
      solution: "n = int(input())\nguruh = []\nfor s in input().split():\n    guruh.append(int(s))\nsanoq = [0, 0, 0, 0, 0]\nfor g in guruh:\n    sanoq[g] += 1\nmashina = sanoq[4] + sanoq[3]\nikki = sanoq[2]\nbir = sanoq[1]\nif bir >= sanoq[3]:\n    bir -= sanoq[3]\nelse:\n    bir = 0\nmashina += ikki // 2\nif ikki % 2 == 1:\n    mashina += 1\n    if bir >= 2:\n        bir -= 2\n    else:\n        bir = 0\nmashina += (bir + 3) // 4\nprint(mashina)",
      hint: "Har guruh oʻlchamini sanab ol. 4 lar alohida, 3 larga bittadan 1 qoʻshiladi, 2 lar juftlanadi, qolgan 1 lar toʻrttadan.",
      rating: 1100,
      tags: ["roʻyxat", "matematika"],
      manba: { kod: "158B", nom: "Taxi", cfTags: ["greedy", "implementation", "math"], url: "https://codeforces.com/problemset/problem/158/B" },
      animatsiya: null,
    },
    {
      id: "cf-qurtlar",
      tartib: 15,
      qadam: 200000,
      title: "Olma uyumlari",
      what: "n ta uyumda olmalar bor: 1-uyumda a1 ta, 2-uyumda a2 ta va hokazo. Olmalar ketma-ket raqamlangan: 1-uyumdagilar 1 dan boshlab, keyin 2-uyumdagilar davom etadi. Berilgan raqamli olma qaysi uyumda ekanini toping.",
      kirish: "Birinchi satrda n (1 ≤ n ≤ 1000), ikkinchida n ta son, uchinchida m (savollar soni, 1 ≤ m ≤ 200), toʻrtinchida m ta raqam. Uyumlar va savollar koʻp — har savol uchun uyumlarni boshidan sanab chiqish sekin.",
      chiqish: "Har savol uchun uyum raqami — alohida satrda.",
      namuna: { stdin: ["5", "2 7 3 4 9", "3", "1 25 11"], out: ["1", "5", "3"] },
      tests: [["1", "1", "1", "1"], ["3", "1 1 1", "3", "1 2 3"], ["4", "5 5 5 5", "2", "6 20"], ["2", "3 3", "4", "1 3 4 6"], ["3", "2 2 2", "2", "6 5"], ["2", "1 5", "1", "2"], KATTA_QURTLAR],
      solution: "n = int(input())\na = []\nfor s in input().split():\n    a.append(int(s))\nm = int(input())\nsavol = []\nfor s in input().split():\n    savol.append(int(s))\nyigindi = []\njami = 0\nfor x in a:\n    jami += x\n    yigindi.append(jami)\nfor q in savol:\n    chap = 0\n    ong = n - 1\n    javob = 0\n    while chap <= ong:\n        orta = (chap + ong) // 2\n        if yigindi[orta] >= q:\n            javob = orta + 1\n            ong = orta - 1\n        else:\n            chap = orta + 1\n    print(javob)",
      hint: "Avval toʻplanuvchi yigʻindini yasa: har uyumgacha jami nechta olma bor. Keyin har savolga ikkilik izlash bilan javob ber.",
      rating: 1200,
      tags: ["izlash", "roʻyxat"],
      manba: { kod: "474B", nom: "Worms", cfTags: ["binary search", "implementation"], url: "https://codeforces.com/problemset/problem/474/B" },
      animatsiya: null,
    },
  ];

  // Olimpiada darajasi (2026-10-02): reyting 700–1400, har masala ikki gʻoyani birlashtiradi.
  // Codeforces gʻoyasi olinganlarida `manba` bor (rating va cfTags — CF API dan, 2026-10-02); shartlar oʻzimizniki.
  //
  // `qadam` — masalaga xos qadam chegarasi (samaradorlik sinovi). Umumiy chegara 3 000 000, lekin
  // `qadam: 200000` yozilgan masalada katta test samarasiz (O(n·q) yoki O(n²)) yechimni shu chegaraga urdiradi;
  // toʻplanuvchi yigʻindi / ikkilik izlash bilan yozilgan yechim bemalol oʻtadi (eng ogʻiri ≈ 16 000 qadam).
  const KATTA_ORALIQ = (() => {
    const satrlar = ["1000", ketma(1000, (i) => ((i * 7919) % 2001) - 1000), "200"];
    for (let j = 1; j <= 200; j++) satrlar.push((1 + (j % 50)) + " " + (1000 - (j % 7)));
    return satrlar;
  })();
  const KATTA_ICHIMLIK = (() => {
    const satrlar = ["1000", ketma(1000, (i) => 1 + ((i * 104729) % 1000000007)), "100"];
    for (let j = 1; j <= 100; j++) satrlar.push(String(1 + ((j * 999983) % 1000000007)));
    return satrlar;
  })();
  const KATTA_BALANS = ["999", ketma(999, (i) => (i === 500 ? 0 : 1))];

  const OLIMPIADA = [
    {
      id: "tanga-eng-kam",
      tartib: 1,
      rating: 700,
      tags: ["for", "matematika"],
      title: "Eng kam tanga",
      what: "Doʻkonda 1, 5, 10, 20 va 50 soʻmlik tangalar bor, har biridan istagancha. n soʻmni iloji boricha kam tanga bilan toʻlash kerak. Eng kamida nechta tanga kerak boʻladi?",
      kirish: "Bitta butun son n (0 ≤ n ≤ 1 000 000).",
      chiqish: "Bitta son — tangalar soni.",
      namuna: { stdin: ["87"], out: ["6"] },
      tests: [["0"], ["1"], ["50"], ["49"], ["99"], ["1000000"], ["30"], ["15"]],
      solution: "n = int(input())\nsoni = 0\nfor t in [50, 20, 10, 5, 1]:\n    soni += n // t\n    n = n % t\nprint(soni)",
      hint: "Avval eng katta tangadan iloji boricha koʻp ol, keyin qolgan summa bilan keyingi tangaga oʻt. Nolni ham unutma: unga tanga kerak emas.",
      animatsiya: null,
    },
    {
      id: "keyingi-tur",
      tartib: 2,
      rating: 800,
      tags: ["roʻyxat", "shart"],
      title: "Keyingi turga kim oʻtadi",
      what: "Olimpiadaning saralash bosqichida n ishtirokchi qatnashdi. Ballar kamayish tartibida berilgan: birinchisi eng koʻp ball olgan. Keyingi turga k-oʻrindagi ishtirokchining balidan kam boʻlmagan ball toʻplagan hamma oʻtadi — lekin nol ball bilan oʻtib boʻlmaydi. Nechta ishtirokchi keyingi turga oʻtadi?",
      kirish: "Birinchi satrda n va k (1 ≤ k ≤ n ≤ 50). Ikkinchi satrda n ta ball (0 dan 100 gacha), kamayish tartibida; teng ballar boʻlishi mumkin.",
      chiqish: "Bitta son — oʻtganlar soni.",
      namuna: { stdin: ["8 5", "10 9 8 7 7 7 5 5"], out: ["6"] },
      tests: [["4 2", "0 0 0 0"], ["1 1", "100"], ["5 3", "5 5 5 5 5"], ["6 4", "9 8 7 0 0 0"], ["3 3", "10 5 1"], ["7 2", "50 50 50 50 1 1 1"], ["5 5", "9 8 7 6 0"]],
      solution: "s = input().split()\nn = int(s[0])\nk = int(s[1])\na = []\nfor t in input().split():\n    a.append(int(t))\nchegara = a[k - 1]\nsoni = 0\nfor x in a:\n    if x >= chegara and x > 0:\n        soni += 1\nprint(soni)",
      hint: "Chegara — k-oʻrindagi ball, roʻyxatda uning indeksi k − 1. Shartda ikki talab bor: chegaradan kam emas VA noldan katta.",
      manba: { kod: "158A", nom: "Next Round", cfTags: ["*special", "implementation"], url: "https://codeforces.com/problemset/problem/158/A" },
      animatsiya: null,
    },
    {
      id: "uzun-sozlar",
      tartib: 3,
      rating: 800,
      tags: ["satr", "shart", "for"],
      title: "Juda uzun soʻzlar",
      what: "Dasturchilar juda uzun soʻzlarni qisqartiradi: soʻzning birinchi harfi, oʻrtadagi harflar soni va oxirgi harfi yoziladi. Masalan, «lokalizatsiya» → «l11a». Soʻz 10 harfdan uzun boʻlsa qisqartiriladi, aks holda oʻzgarmaydi. n ta soʻz berilgan — har birini shu qoida bilan chiqar.",
      kirish: "Birinchi satrda n (1 ≤ n ≤ 100). Keyingi n satrda bittadan soʻz: kichik lotin harflari, uzunligi 1 dan 100 gacha.",
      chiqish: "n ta satr — har soʻz qisqartirilgan yoki oʻzgarmagan holda.",
      namuna: { stdin: ["4", "soz", "lokalizatsiya", "kompyuterlar", "olma"], out: ["soz", "l11a", "k10r", "olma"] },
      tests: [
        ["1", "abcdefghij"],
        ["1", "abcdefghijk"],
        ["2", "a", "ab"],
        ["3", "qabilamaktabi", "dasturlashtirish", "x"],
        ["1", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"],
        ["5", "informatika", "olimpiada", "pneumonoultramicroscopicsilicovolcanoconiosis", "ab", "abcdefghijkl"],
      ],
      solution: "n = int(input())\nfor i in range(n):\n    s = input()\n    if len(s) > 10:\n        print(s[0] + str(len(s) - 2) + s[len(s) - 1])\n    else:\n        print(s)",
      hint: "len(s) 10 dan katta boʻlsa: birinchi harf + (uzunlik − 2) + oxirgi harf. Sonni harfga qoʻshish uchun str() kerak. Aynan 10 harfli soʻz oʻzgarmaydi.",
      manba: { kod: "71A", nom: "Way Too Long Words", cfTags: ["strings"], url: "https://codeforces.com/problemset/problem/71/A" },
      animatsiya: null,
    },
    {
      id: "navbat-maktab",
      tartib: 4,
      rating: 800,
      tags: ["satr", "roʻyxat", "while"],
      title: "Oshxona navbati",
      what: "Oshxona oldida n bola navbatda turibdi: oʻgʻil bolalar (B) va qizlar (G). Oʻgʻil bolalar odobli: har soniyada, agar oʻgʻil bola bevosita qiz boladan oldin tursa, ular oʻrin almashadi — bunday hamma juftlik bir vaqtda almashadi. t soniyadan keyin navbat qanday koʻrinishda boʻladi?",
      kirish: "Birinchi satrda n va t (1 ≤ n, t ≤ 50). Ikkinchi satrda n ta harf: faqat B va G, birinchi harf — navbatning boshi.",
      chiqish: "t soniyadan keyingi navbat — n ta harf.",
      namuna: { stdin: ["5 1", "BGGBG"], out: ["GBGGB"] },
      tests: [["5 2", "BGGBG"], ["4 1", "GGGB"], ["3 10", "BBB"], ["6 50", "BBBGGG"], ["1 1", "B"], ["4 1", "BGBG"], ["7 3", "BGBGBGG"], ["8 1", "BBGGBBGG"]],
      solution: "s = input().split()\nn = int(s[0])\nt = int(s[1])\nq = []\nfor h in input():\n    q.append(h)\nfor sekund in range(t):\n    i = 0\n    while i < n - 1:\n        if q[i] == \"B\" and q[i + 1] == \"G\":\n            q[i] = \"G\"\n            q[i + 1] = \"B\"\n            i += 2\n        else:\n            i += 1\nnatija = \"\"\nfor h in q:\n    natija = natija + h\nprint(natija)",
      hint: "Satrni roʻyxatga oʻgir — uni oʻzgartirib boʻladi. Almashgan juftlikni shu soniyada yana tekshirma: i ni 2 ga oshir, aks holda bola bir soniyada ikki qadam orqaga ketadi.",
      manba: { kod: "266B", nom: "Queue at the School", cfTags: ["constructive algorithms", "graph matchings", "implementation", "shortest paths"], url: "https://codeforces.com/problemset/problem/266/B" },
      animatsiya: null,
    },
    {
      id: "onlikdan-asos",
      tartib: 5,
      rating: 800,
      tags: ["while", "raqamlar", "satr"],
      title: "Oʻnlikdan b-likka",
      what: "Son n va asos b berilgan. n ni b-lik sanoq tizimida yoz. Raqamlar 0 dan b − 1 gacha boʻladi (b ≤ 10, shuning uchun harf kerak emas). Nolning yozuvi — bitta 0.",
      kirish: "Ikki satrda n (0 ≤ n ≤ 10⁹) va b (2 ≤ b ≤ 10).",
      chiqish: "n ning b-lik yozuvi.",
      namuna: { stdin: ["10", "2"], out: ["1010"] },
      tests: [["0", "5"], ["255", "2"], ["100", "10"], ["7", "7"], ["1000000000", "3"], ["8", "8"], ["1", "2"], ["999", "9"]],
      solution: "n = int(input())\nb = int(input())\nif n == 0:\n    print(0)\nelse:\n    s = \"\"\n    while n > 0:\n        s = str(n % b) + s\n        n = n // b\n    print(s)",
      hint: "Qoldiqlar oxiridan boshiga yoziladi — har qadamda yangi raqamni satrning OLDIGA qoʻsh. Nol alohida holat: sikl bir marta ham aylanmaydi.",
      animatsiya: null,
    },
    {
      id: "futbol",
      tartib: 6,
      rating: 900,
      tags: ["satr", "for", "shart"],
      title: "Xavfli vaziyat",
      what: "Futbol maydonida ikki jamoa bor: 0 va 1. Oʻyinchilar bir qator boʻlib turibdi va har biri jamoasining raqami bilan yozilgan. Agar bir jamoaning kamida 7 oʻyinchisi ketma-ket tursa, vaziyat xavfli hisoblanadi. Vaziyat xavflimi?",
      kirish: "Bitta satr: faqat 0 va 1 belgilari, uzunligi 1 dan 100 gacha.",
      chiqish: 'Xavfli boʻlsa "ha", aks holda "yoʻq".',
      namuna: { stdin: ["001001"], out: ["yoʻq"] },
      tests: [["1000000001"], ["1111111"], ["111111"], ["0"], ["0101010101010101"], ["00000001111111"], ["1111110111111"], ["0000000"]],
      solution: "s = input()\nqator = 1\nxavfli = False\nfor i in range(1, len(s)):\n    if s[i] == s[i - 1]:\n        qator += 1\n    else:\n        qator = 1\n    if qator >= 7:\n        xavfli = True\nif xavfli:\n    print(\"ha\")\nelse:\n    print(\"yoʻq\")",
      hint: "Ketma-ket bir xil belgilar uzunligini sanab bor: oldingisi bilan teng boʻlsa oshir, aks holda 1 dan boshla. 6 ta — hali xavfli emas, 7 ta — xavfli.",
      manba: { kod: "96A", nom: "Football", cfTags: ["implementation", "strings"], url: "https://codeforces.com/problemset/problem/96/A" },
      animatsiya: null,
    },
    {
      id: "egizaklar",
      tartib: 7,
      rating: 900,
      tags: ["saralash", "roʻyxat", "while"],
      title: "Egizaklarning tangalari",
      what: "Egizaklarda n ta tanga bor, har birining qiymati maʼlum. Sen tangalarning bir qismini olasan; olganlaringning yigʻindisi qolganlarning yigʻindisidan qatʼiy koʻp boʻlishi kerak. Buning uchun eng kamida nechta tanga olishing kerak?",
      kirish: "Birinchi satrda n (1 ≤ n ≤ 100). Ikkinchi satrda n ta tanga qiymati (1 dan 100 gacha).",
      chiqish: "Bitta son — eng kam tangalar soni.",
      namuna: { stdin: ["2", "3 3"], out: ["2"] },
      tests: [["3", "2 1 2"], ["1", "5"], ["4", "1 1 1 1"], ["5", "100 1 1 1 1"], ["6", "1 2 3 4 5 6"], ["3", "1 2 3"], ["7", "7 7 7 7 7 7 7"], ["5", "1 2 100 2 1"]],
      solution: "n = int(input())\na = []\nfor t in input().split():\n    a.append(int(t))\na = sorted(a)\njami = 0\nfor x in a:\n    jami += x\nolingan = 0\nsoni = 0\ni = len(a) - 1\nwhile olingan <= jami - olingan:\n    olingan += a[i]\n    soni += 1\n    i -= 1\nprint(soni)",
      hint: "Eng qimmat tangalardan boshlab ol — shunda kamroq tanga kerak boʻladi. sorted() oʻsish tartibida beradi: oxiridan boshiga qarab yur, olganing qolganidan oshguncha.",
      manba: { kod: "160A", nom: "Twins", cfTags: ["greedy", "sortings"], url: "https://codeforces.com/problemset/problem/160/A" },
      animatsiya: null,
    },
    {
      id: "ikki-gramm",
      tartib: 8,
      rating: 900,
      tags: ["satr", "for"],
      title: "Ikki-gramm",
      what: "Satrdagi ketma-ket ikki harfdan iborat boʻlakni ikki-gramm deymiz. Katta lotin harflaridan iborat satr berilgan. Unda eng koʻp uchraydigan ikki-grammni top; boʻlaklar ustma-ust tushishi mumkin («AAA» da «AA» ikki marta uchraydi). Bir nechtasi teng uchrasa — satrda birinchi boshlanganini chiqar.",
      kirish: "Birinchi satrda n (2 ≤ n ≤ 100), ikkinchida n ta katta lotin harfi.",
      chiqish: "Ikki harf.",
      namuna: { stdin: ["7", "ABACABA"], out: ["AB"] },
      tests: [["5", "ZZZAA"], ["2", "AB"], ["4", "AAAA"], ["6", "ABCDEF"], ["9", "BBAABBAAB"], ["10", "XYXYXYXYXY"], ["3", "CAC"], ["12", "QQWWQQWWQQWW"]],
      solution: "n = int(input())\ns = input()\nbest = \"\"\nbestSoni = 0\nfor i in range(n - 1):\n    juft = s[i:i + 2]\n    soni = 0\n    for j in range(n - 1):\n        if s[j:j + 2] == juft:\n            soni += 1\n    if soni > bestSoni:\n        bestSoni = soni\n        best = juft\nprint(best)",
      hint: "Har ikki-gramm (s[i:i + 2]) uchun u satrda necha marta uchrashini ichki sikl bilan sana. Eng koʻpini saqlab bor; teng boʻlsa almashtirma — qatʼiy > bilan solishtir.",
      manba: { kod: "977B", nom: "Two-gram", cfTags: ["implementation", "strings"], url: "https://codeforces.com/problemset/problem/977/B" },
      animatsiya: null,
    },
    {
      id: "juft-toq-orin",
      tartib: 9,
      rating: 900,
      qadam: 200000,
      tags: ["matematika", "shart"],
      title: "Avval toqlar, keyin juftlar",
      what: "1 dan n gacha sonlar shunday yozildi: avval hamma toq sonlar oʻsish tartibida, keyin hamma juft sonlar oʻsish tartibida. Masalan, n = 7 uchun: 1, 3, 5, 7, 2, 4, 6. Shu qatorda k-oʻrinda qaysi son turadi? Diqqat: n juda katta boʻlishi mumkin — qatorni yozib chiqib boʻlmaydi.",
      kirish: "Bitta satrda n va k (1 ≤ k ≤ n ≤ 10¹²).",
      chiqish: "Bitta son.",
      namuna: { stdin: ["10 3"], out: ["5"] },
      tests: [["7 7"], ["1 1"], ["1000000000000 1000000000000"], ["1000000000000 500000000000"], ["1000000000000 500000000001"], ["8 4"], ["8 5"], ["9 5"]],
      solution: "s = input().split()\nn = int(s[0])\nk = int(s[1])\ntoqlar = (n + 1) // 2\nif k <= toqlar:\n    print(2 * k - 1)\nelse:\n    print(2 * (k - toqlar))",
      hint: "Toq sonlar nechta? (n + 1) // 2. k shundan oshmasa — bu k-toq son; oshsa — (k − toqlar)-juft son. Sikl bilan 10¹² gacha yurib boʻlmaydi, formula kerak.",
      manba: { kod: "318A", nom: "Even Odds", cfTags: ["math"], url: "https://codeforces.com/problemset/problem/318/A" },
      animatsiya: null,
    },
    {
      id: "asosdan-onlik",
      tartib: 10,
      rating: 900,
      tags: ["satr", "raqamlar", "for"],
      title: "b-likdan oʻnlikka",
      what: "b-lik sanoq tizimida yozilgan son berilgan (b ≤ 10, demak faqat raqamlar). Uni oʻnlik tizimda chiqar. Yozuv uzun boʻlishi mumkin — javob int ga sigʻadi (Python katta sonlarni biladi).",
      kirish: "Birinchi satrda asos b (2 ≤ b ≤ 10). Ikkinchi satrda b-lik sonning yozuvi — raqamlar satri, uzunligi 1 dan 30 gacha, hamma raqami b dan kichik. Boshida nollar boʻlishi mumkin.",
      chiqish: "Oʻnlik son.",
      namuna: { stdin: ["2", "1010"], out: ["10"] },
      tests: [["2", "0"], ["10", "12345"], ["3", "000012"], ["2", "111111111111111111111111111111"], ["8", "777"], ["5", "4321"], ["9", "10"], ["7", "66666666666666666666"]],
      solution: "b = int(input())\ns = input()\nn = 0\nfor h in s:\n    n = n * b + int(h)\nprint(n)",
      hint: "Chapdan oʻngga yur: natija = natija × b + raqam. Bu — sonni teskari oʻgirishdagi t = t * 10 + … usuli, faqat 10 oʻrniga b.",
      animatsiya: null,
    },
    {
      id: "juftliklar-yigindisi",
      tartib: 11,
      rating: 1000,
      tags: ["for", "kombinatorika", "roʻyxat"],
      title: "Yigʻindisi k boʻlgan juftliklar",
      what: "n ta son va k berilgan. Shunday (i, j) juftliklar nechta (i < j), ularning yigʻindisi aynan k ga teng? Sonlar takrorlanishi mumkin — har juftlik oʻrinlari boʻyicha alohida sanaladi: «2 2 2» da yigʻindisi 4 boʻlgan 3 ta juftlik bor.",
      kirish: "Birinchi satrda n va k (1 ≤ n ≤ 100, −1000 ≤ k ≤ 1000). Ikkinchi satrda n ta butun son (−1000 dan 1000 gacha).",
      chiqish: "Bitta son — juftliklar soni.",
      namuna: { stdin: ["5 6", "1 5 2 4 3"], out: ["2"] },
      tests: [["4 4", "2 2 2 2"], ["1 2", "1"], ["3 0", "-1 1 0"], ["6 10", "5 5 5 5 5 5"], ["5 100", "1 2 3 4 5"], ["4 -3", "-1 -2 -3 0"], ["7 7", "0 7 3 4 7 0 3"], ["2 0", "0 0"]],
      solution: "s = input().split()\nn = int(s[0])\nk = int(s[1])\na = []\nfor t in input().split():\n    a.append(int(t))\nsoni = 0\nfor i in range(n):\n    for j in range(i + 1, n):\n        if a[i] + a[j] == k:\n            soni += 1\nprint(soni)",
      hint: "Ikki sikl: tashqi i, ichki j faqat i + 1 dan boshlanadi — shunda har juftlik aynan bir marta sanaladi («Jamoa tanlash» oʻyinidagi juftlar kabi).",
      animatsiya: null,
    },
    {
      id: "zinapoya-qadam",
      tartib: 12,
      rating: 1000,
      tags: ["matematika", "for", "shart"],
      title: "Chiroyli zinapoya",
      what: "Zinapoyada n ta pogʻona bor. Har qadamda 1 yoki 2 pogʻona koʻtarilish mumkin. Qadamlar soni m ga karrali boʻlishi kerak — shunday yurish chiroyli hisoblanadi. Shunday eng kam qadamlar sonini top. Iloji boʻlmasa, −1 chiqar.",
      kirish: "Bitta satrda n va m (1 ≤ n ≤ 10000, 1 ≤ m ≤ 10).",
      chiqish: "Eng kam qadamlar soni yoki −1.",
      namuna: { stdin: ["10 2"], out: ["6"] },
      tests: [["3 5"], ["1 1"], ["1 2"], ["2 2"], ["7 3"], ["10000 10"], ["9 9"], ["5 1"], ["9999 10"]],
      solution: "s = input().split()\nn = int(s[0])\nm = int(s[1])\njavob = -1\nfor q in range((n + 1) // 2, n + 1):\n    if q % m == 0 and javob == -1:\n        javob = q\nprint(javob)",
      hint: "Qadamlar soni eng kami (n + 1) // 2 (koʻproq ikkitalab), eng koʻpi n (hammasi bittalab) — oraliqdagi har son boʻla oladi. Shu oraliqda m ga boʻlinadigan eng kichigini top; boʻlmasa −1.",
      manba: { kod: "476A", nom: "Dreamoon and Stairs", cfTags: ["implementation", "math"], url: "https://codeforces.com/problemset/problem/476/A" },
      animatsiya: null,
    },
    {
      id: "ajdarlar",
      tartib: 13,
      rating: 1000,
      tags: ["saralash", "roʻyxat", "shart"],
      title: "Ajdarlar bilan jang",
      what: "Qahramonning kuchi s. Yoʻlda n ta ajdar bor; har birining kuchi x, va u yengilsa, qahramon kuchiga y bonus qoʻshiladi. Qahramon ajdarni faqat kuchi undan qatʼiy katta boʻlganda yengadi. Ajdarlar bilan istalgan tartibda jang qilish mumkin. Hammasini yengib boʻladimi?",
      kirish: "Birinchi satrda s va n (1 ≤ s ≤ 10⁴, 1 ≤ n ≤ 100). Keyingi n satrda x va y (1 ≤ x ≤ 10⁴, 0 ≤ y ≤ 10⁴).",
      chiqish: 'Hammasini yengsa "ha", aks holda "yoʻq".',
      namuna: { stdin: ["2 2", "1 99", "100 0"], out: ["ha"] },
      tests: [["10 1", "100 100"], ["5 1", "5 10"], ["5 2", "4 0", "4 0"], ["2 3", "3 0", "1 10", "2 5"], ["3 3", "10 0", "5 0", "6 0"], ["100 1", "1 0"], ["3 2", "3 100", "1 1"], ["1 2", "1 100", "1 100"]],
      solution: "s = input().split()\nkuch = int(s[0])\nn = int(s[1])\najdarlar = []\nfor i in range(n):\n    t = input().split()\n    ajdarlar.append([int(t[0]), int(t[1])])\najdarlar = sorted(ajdarlar)\nyutdi = True\nfor a in ajdarlar:\n    if kuch > a[0]:\n        kuch += a[1]\n    else:\n        yutdi = False\nif yutdi:\n    print(\"ha\")\nelse:\n    print(\"yoʻq\")",
      hint: "Avval kuchsiz ajdarlarni yeng — bonus yigʻiladi, keyin kuchlilarga kuch yetadi. [x, y] juftliklar roʻyxatini sorted() birinchi son (x) boʻyicha tartiblaydi. Teng kuch — yengilmaydi.",
      manba: { kod: "230A", nom: "Dragons", cfTags: ["greedy", "sortings"], url: "https://codeforces.com/problemset/problem/230/A" },
      animatsiya: null,
    },
    {
      id: "satr-vazifasi",
      tartib: 14,
      rating: 1000,
      tags: ["satr", "for", "shart"],
      title: "Satrni qayta yozish",
      what: "Satrni shunday oʻzgartir: hamma unli harflarni oʻchir (bu masalada unlilar: a, e, i, o, u, y), qolgan har bir harf oldiga nuqta qoʻy va hamma harfni kichik qil. Masalan, «tour» → «.t.r».",
      kirish: "Bitta satr — lotin harflari, katta va kichik aralash, uzunligi 1 dan 100 gacha.",
      chiqish: "Natija satri (hamma harf unli boʻlsa — boʻsh satr).",
      namuna: { stdin: ["Codeforces"], out: [".c.d.f.r.c.s"] },
      tests: [["tour"], ["aBAcAba"], ["AEIOUY"], ["xyz"], ["Q"], ["PYTHON"], ["Yyyyy"], ["QabilaMaktabi"]],
      solution: "s = input().lower()\nnatija = \"\"\nfor h in s:\n    if h not in \"aeiouy\":\n        natija = natija + \".\" + h\nprint(natija)",
      hint: "Avval lower(), keyin har harfni tekshir: unli boʻlmasa, natijaga «.» va harfni qoʻsh. y ham unlilar roʻyxatida — buni unutish eng koʻp uchraydigan xato.",
      manba: { kod: "118A", nom: "String Task", cfTags: ["implementation", "strings"], url: "https://codeforces.com/problemset/problem/118/A" },
      animatsiya: null,
    },
    {
      id: "oraliq-sorovlar",
      tartib: 15,
      rating: 1000,
      qadam: 200000,
      tags: ["roʻyxat", "for"],
      title: "Oraliq yigʻindisi — koʻp soʻrov",
      what: "n ta son berilgan. Keyin q ta soʻrov keladi; har soʻrovda ikki son l va r. Har soʻrov uchun l-dan r-gacha (ikkalasi ham kiradi, oʻrinlar 1 dan sanaladi) sonlar yigʻindisini chiqar. Diqqat: soʻrovlar koʻp va roʻyxat uzun — har soʻrovda qaytadan qoʻshib chiqsang, vaqt yetmaydi.",
      kirish: "Birinchi satrda n (1 ≤ n ≤ 1000). Ikkinchi satrda n ta butun son (−10⁶ dan 10⁶ gacha). Uchinchi satrda q (1 ≤ q ≤ 200). Keyingi q satrda l va r (1 ≤ l ≤ r ≤ n).",
      chiqish: "q ta satr — har soʻrovning javobi.",
      namuna: { stdin: ["5", "1 2 3 4 5", "3", "1 5", "2 3", "4 4"], out: ["15", "5", "4"] },
      tests: [
        ["1", "7", "1", "1 1"],
        ["4", "-1 -2 -3 -4", "2", "1 4", "2 2"],
        ["6", "1000000 1000000 1000000 1000000 1000000 1000000", "1", "1 6"],
        ["5", "5 0 0 0 5", "3", "2 4", "1 1", "5 5"],
        ["3", "1 -1 1", "3", "1 2", "2 3", "1 3"],
        ["10", "3 1 4 1 5 9 2 6 5 3", "4", "1 10", "3 7", "6 6", "9 10"],
        KATTA_ORALIQ,
      ],
      solution: "n = int(input())\na = []\nfor t in input().split():\n    a.append(int(t))\npre = [0]\nfor x in a:\n    pre.append(pre[len(pre) - 1] + x)\nq = int(input())\nfor i in range(q):\n    t = input().split()\n    l = int(t[0])\n    r = int(t[1])\n    print(pre[r] - pre[l - 1])",
      hint: "Toʻplanuvchi yigʻindi: pre[i] — birinchi i ta sonning yigʻindisi, pre[0] = 0. Shunda l..r yigʻindisi = pre[r] − pre[l − 1] — har soʻrovga bitta ayirish.",
      animatsiya: null,
    },
    {
      id: "ichimlik",
      tartib: 16,
      rating: 1100,
      qadam: 200000,
      tags: ["izlash", "saralash", "roʻyxat"],
      title: "Nechta doʻkonda sotib olaman",
      what: "Shaharda n doʻkon bor, har birida sevimli ichimlik oʻz narxida sotiladi. Bola q kun davomida har kuni maʼlum m soʻm bilan chiqadi va shu kuni nechta doʻkonda ichimlikni sotib ola olishini bilmoqchi — yaʼni narxi m dan oshmaydigan doʻkonlar sonini. Har kun uchun javob ber. Doʻkonlar koʻp, kunlar ham — har kuni hamma doʻkonni koʻrib chiqish sekin.",
      kirish: "Birinchi satrda n (1 ≤ n ≤ 1000). Ikkinchi satrda n ta narx (1 dan 10⁹ gacha). Uchinchi satrda q (1 ≤ q ≤ 100). Keyingi q satrda bittadan m (1 ≤ m ≤ 10⁹).",
      chiqish: "q ta satr — har kun uchun doʻkonlar soni.",
      namuna: { stdin: ["5", "3 10 8 6 11", "4", "1", "10", "3", "11"], out: ["0", "4", "1", "5"] },
      tests: [
        ["1", "5", "2", "4", "5"],
        ["3", "7 7 7", "3", "6", "7", "8"],
        ["4", "1000000000 1 1000000000 1", "2", "999999999", "1000000000"],
        ["6", "6 5 4 3 2 1", "3", "3", "1", "6"],
        ["5", "2 4 6 8 10", "5", "1", "2", "5", "9", "100"],
        KATTA_ICHIMLIK,
      ],
      solution: "n = int(input())\na = []\nfor t in input().split():\n    a.append(int(t))\na = sorted(a)\nq = int(input())\nfor i in range(q):\n    m = int(input())\n    chap = 0\n    ong = n\n    while chap < ong:\n        orta = (chap + ong) // 2\n        if a[orta] <= m:\n            chap = orta + 1\n        else:\n            ong = orta\n    print(chap)",
      hint: "Narxlarni sarala. Keyin har m uchun ikkilik izlash bilan «m dan katta BIRINCHI narx» oʻrnini top — shu oʻrin javobning oʻzi (undan oldingi hamma narx m dan oshmaydi).",
      manba: { kod: "706B", nom: "Interesting drink", cfTags: ["binary search", "dp", "implementation"], url: "https://codeforces.com/problemset/problem/706/B" },
      animatsiya: null,
    },
    {
      id: "balans-nuqtasi",
      tartib: 17,
      rating: 1100,
      qadam: 200000,
      tags: ["roʻyxat", "matematika", "for"],
      title: "Muvozanat nuqtasi",
      what: "n ta son berilgan. Shunday eng kichik oʻrin i ni top (1 dan sanaladi): i-dan chapdagi sonlar yigʻindisi i-dan oʻngdagilar yigʻindisiga teng boʻlsin. i-oʻrindagi sonning oʻzi hisobga olinmaydi; chapda yoki oʻngda son boʻlmasa, u tomonning yigʻindisi 0. Bunday oʻrin boʻlmasa, −1 chiqar.",
      kirish: "Birinchi satrda n (1 ≤ n ≤ 1000). Ikkinchi satrda n ta butun son (−1000 dan 1000 gacha).",
      chiqish: "Oʻrin raqami yoki −1.",
      namuna: { stdin: ["6", "1 7 3 6 5 6"], out: ["4"] },
      tests: [["1", "5"], ["3", "1 2 3"], ["5", "2 0 2 0 2"], ["4", "0 0 0 0"], ["5", "-1 1 5 1 -1"], ["2", "3 3"], ["7", "1 2 3 100 3 2 1"], KATTA_BALANS],
      solution: "n = int(input())\na = []\nfor t in input().split():\n    a.append(int(t))\njami = 0\nfor x in a:\n    jami += x\nchap = 0\njavob = -1\nfor i in range(n):\n    ong = jami - chap - a[i]\n    if chap == ong and javob == -1:\n        javob = i + 1\n    chap += a[i]\nprint(javob)",
      hint: "Hamma sonning yigʻindisini BIR marta hisobla. Keyin chapdan yurib chap yigʻindini toʻplab bor: oʻng = jami − chap − a[i]. Har oʻrin uchun ikki tomonni qaytadan qoʻshish — n² ish, u sigʻmaydi.",
      animatsiya: null,
    },
    {
      id: "kvadrat-ildiz",
      tartib: 18,
      rating: 1100,
      qadam: 200000,
      tags: ["izlash", "while", "matematika"],
      title: "Butun kvadrat ildiz",
      what: "Juda katta son n berilgan. Kvadrati n dan oshmaydigan eng katta butun son x ni top: x·x ≤ n, lekin (x + 1)·(x + 1) > n. Diqqat: n 10¹⁸ gacha — 1 dan boshlab sanab chiqish juda uzoq, oraliqni yarmiga boʻlib bor.",
      kirish: "Bitta butun son n (0 ≤ n ≤ 10¹⁸).",
      chiqish: "Bitta son — x.",
      namuna: { stdin: ["15"], out: ["3"] },
      tests: [["0"], ["1"], ["16"], ["1000000000000000000"], ["999999999999999999"], ["2"], ["99"], ["100"], ["123456789012345678"]],
      solution: "n = int(input())\nchap = 0\nong = n\nwhile chap < ong:\n    orta = (chap + ong + 1) // 2\n    if orta * orta <= n:\n        chap = orta\n    else:\n        ong = orta - 1\nprint(chap)",
      hint: "Javob ustida ikkilik izlash: oʻrtadagi x ning kvadrati n dan oshmasa — javob x yoki undan katta (chap = x), aks holda kichik (ong = x − 1). 60 qadamda topiladi. (chap + ong + 1) // 2 — chegara qotib qolmasligi uchun.",
      animatsiya: null,
    },
    {
      id: "k-bolinmaydigan",
      tartib: 19,
      rating: 1200,
      tags: ["matematika"],
      title: "n ga boʻlinmaydigan k-son",
      what: "n va k berilgan. n ga boʻlinmaydigan musbat butun sonlarni oʻsish tartibida yozsak (masalan, n = 3 uchun: 1, 2, 4, 5, 7, 8, …), shu qatorda k-oʻrinda qaysi son turadi? k juda katta — qatorni yozib chiqib boʻlmaydi.",
      kirish: "Bitta satrda n va k (2 ≤ n ≤ 10⁹, 1 ≤ k ≤ 10⁹).",
      chiqish: "Bitta son.",
      namuna: { stdin: ["3 7"], out: ["10"] },
      tests: [["4 12"], ["2 1000000000"], ["7 97"], ["1000000000 1000000000"], ["2 1"], ["3 1"], ["3 2"], ["3 3"], ["5 4"], ["5 5"]],
      solution: "s = input().split()\nn = int(s[0])\nk = int(s[1])\nprint(k + (k - 1) // (n - 1))",
      hint: "Har n − 1 ta «yaxshi» sondan keyin bitta «yomon» (n ga karrali) son oʻtkazib yuboriladi. k-yaxshi songacha nechta yomon son oʻtkazilganini hisobla va k ga qoʻsh.",
      manba: { kod: "1352C", nom: "K-th Not Divisible by n", cfTags: ["binary search", "math"], url: "https://codeforces.com/problemset/problem/1352/C" },
      animatsiya: null,
    },
    {
      id: "yuk-tashish",
      tartib: 20,
      rating: 1400,
      tags: ["izlash", "funksiya", "roʻyxat"],
      title: "Yuk mashinalari",
      what: "Konveyerda n ta quti ketma-ket turibdi, har birining ogʻirligi maʼlum. Ularni tartibni buzmasdan k ta yuk mashinasiga boʻlib yuklash kerak: har mashina ketma-ket turgan qutilarning bir boʻlagini oladi, har mashinaga kamida bitta quti tegadi. Eng ogʻir yuklangan mashinaning ogʻirligi iloji boricha kichik boʻlsin. Shu eng kichik qiymatni top.",
      kirish: "Birinchi satrda n va k (1 ≤ k ≤ n ≤ 100). Ikkinchi satrda n ta ogʻirlik (1 dan 1000 gacha).",
      chiqish: "Bitta son — eng ogʻir mashinaning eng kichik mumkin boʻlgan ogʻirligi.",
      namuna: { stdin: ["5 2", "1 2 3 4 5"], out: ["9"] },
      tests: [["1 1", "7"], ["4 4", "1 2 3 4"], ["4 1", "1 2 3 4"], ["7 3", "2 2 2 2 2 2 2"], ["6 2", "1 1 1 1 1 1000"], ["6 3", "10 20 30 40 50 60"], ["5 3", "3 1 4 1 5"], ["9 3", "1 1 1 1 1 1 1 1 1"]],
      solution: "s = input().split()\nn = int(s[0])\nk = int(s[1])\na = []\nfor t in input().split():\n    a.append(int(t))\n\ndef sigadimi(chegara):\n    mashina = 1\n    yuk = 0\n    for x in a:\n        if yuk + x > chegara:\n            mashina += 1\n            yuk = x\n        else:\n            yuk += x\n    return mashina <= k\n\nchap = max(a)\nong = sum(a)\nwhile chap < ong:\n    orta = (chap + ong) // 2\n    if sigadimi(orta):\n        ong = orta\n    else:\n        chap = orta + 1\nprint(chap)",
      hint: "Javob ustida ikkilik izlash. «Chegara X bilan k ta mashinaga sigʻadimi?» — bunga ochkoʻz usul javob beradi: mashinani toʻlguncha yuklayver, sigʻmasa yangisini ol. Sigʻsa — X ni kamaytir, sigʻmasa — oshir. Eng kichik X — eng ogʻir quti, eng kattasi — hammasining yigʻindisi.",
      animatsiya: null,
    },
  ];

  const LEVELS = [
    { id: "oson", title: "Oson", note: "Shart va sikl", problems: OSON },
    { id: "orta", title: "Oʻrta", note: "Raqamlar, roʻyxat va satr", problems: ORTA },
    { id: "qiyin", title: "Qiyin", note: "Bir nechta qadam", problems: QIYIN },
    { id: "cf", title: "Codeforces", note: "Haqiqiy olimpiada masalalari (reyting 800–1200)", problems: CF },
    { id: "olimpiada", title: "Olimpiada", note: "Reyting 700–1400: ikki gʻoyani birlashtirish", problems: OLIMPIADA },
  ];

  const api = { LEVELS, TAGS, OSON, ORTA, QIYIN, CF, OLIMPIADA };

  root.QK = root.QK || {};
  root.QK.bank = api;
  if (typeof module !== "undefined" && module.exports) module.exports = api;
})(typeof window !== "undefined" ? window : globalThis);
