// Kichik Python uchun sinov dasturlari.
// Shu ro'yxat ikki joyda ishlatiladi: python-run.test.js (chiqish o'zgarmaganini tekshiradi)
// va python-parity.test.js (haqiqiy python3 bilan solishtiradi). Dasturlar albatta tugaydi.
const PROGRAMS = [
  { name: "print", code: 'print("Salom, qabila!")' },
  { name: "print ko'p qiymat", code: 'print("a", 1, 2.5, True, None)' },
  { name: "bo'sh print", code: 'print("bir")\nprint()\nprint("ikki")' },
  { name: "qo'shtirnoq ichidagi amal", code: 'print(2 + 3)\nprint("2 + 3")' },
  { name: "sonlar", code: "print(7 + 2, 7 - 2, 7 * 2)" },
  { name: "bo'lish", code: "print(7 / 2, 4 / 2, 7 // 2, 7 % 2)" },
  { name: "manfiy bo'lish", code: "print(-7 // 2, -7 % 3, 7 // -2, 7 % -3)" },
  { name: "daraja", code: "print(2 ** 10, 2 ** 100, 2 ** -1, -2 ** 2)" },
  { name: "amallar tartibi", code: "print(2 + 3 * 4, (2 + 3) * 4, 10 - 2 - 3, 2 ** 3 ** 2)" },
  { name: "kasr sonlar", code: "print(0.1 + 0.2, 1.5 * 2, 10 / 4)" },
  { name: "o'zgaruvchi", code: "x = 5\nx = x + 1\nx += 10\nprint(x)" },
  { name: "almashtirish", code: "a = 1\nb = 2\na, b = b, a\nprint(a, b)" },
  { name: "input", code: "n = int(input())\nm = int(input())\nprint(n + m)", stdin: ["12", "30"] },
  { name: "input matn", code: 's = input()\nprint("Salom,", s)\nprint(len(s))', stdin: ["Alisher"] },
  { name: "int va str", code: 'print(int("42") + 1, str(42) + "!", int(3.9), int(-3.9))' },
  { name: "shart", code: "x = 7\nif x > 5:\n    print('katta')\nelse:\n    print('kichik')" },
  { name: "elif", code: "for b in [95, 80, 60, 30]:\n    if b >= 90:\n        print(5)\n    elif b >= 70:\n        print(4)\n    elif b >= 50:\n        print(3)\n    else:\n        print(2)" },
  { name: "mantiq", code: "x = 7\nprint(x > 5 and x < 10, x < 5 or x == 7, not x == 7)" },
  { name: "zanjirli solishtirish", code: "x = 7\nprint(0 < x < 10, 10 < x < 20)" },
  { name: "while", code: "i = 1\nwhile i <= 5:\n    print(i)\n    i += 1" },
  { name: "yig'indi", code: "s = 0\ni = 1\nwhile i <= 100:\n    s += i\n    i += 1\nprint(s)" },
  { name: "raqamlarni ajratish", code: "n = 5382\nyig = 0\nsoni = 0\nwhile n > 0:\n    yig += n % 10\n    n = n // 10\n    soni += 1\nprint(yig, soni)" },
  { name: "teskari son", code: "n = 1234\nt = 0\nwhile n > 0:\n    t = t * 10 + n % 10\n    n = n // 10\nprint(t)" },
  { name: "break", code: "i = 0\nwhile True:\n    i += 1\n    if i * i > 50:\n        break\nprint(i)" },
  { name: "continue", code: "for i in range(10):\n    if i % 2 == 0:\n        continue\n    print(i)" },
  { name: "for range", code: "for i in range(3):\n    print(i)\nfor i in range(2, 5):\n    print(i)\nfor i in range(10, 0, -3):\n    print(i)" },
  { name: "ichma-ich sikl", code: "for i in range(1, 4):\n    for j in range(1, 4):\n        print(i, 'x', j, '=', i * j)" },
  { name: "naqsh", code: "for i in range(1, 6):\n    print('*' * i)" },
  { name: "ro'yxat", code: "a = [5, 2, 9, 1]\nprint(a, len(a), a[0], a[-1])\na.append(7)\na[1] = 100\nprint(a, sum(a), min(a), max(a), sorted(a))" },
  { name: "ro'yxat bo'ylab", code: "a = [4, 8, 15, 16]\ns = 0\nfor x in a:\n    s += x\nprint(s, s / len(a))" },
  { name: "eng kattasini topish", code: "a = [3, 17, 8, 12]\nbest = a[0]\nfor x in a:\n    if x > best:\n        best = x\nprint(best)" },
  { name: "satr", code: "s = 'qabila'\nprint(s[0], s[-1], s[1:4], s[:3], s[3:], len(s))\nprint(s.upper(), s.lower(), s.count('a'))" },
  { name: "satr bo'ylab", code: "s = 'informatika'\nn = 0\nfor ch in s:\n    if ch in 'aeiou':\n        n += 1\nprint(n)" },
  { name: "split", code: "a = input().split()\nprint(len(a), a[0], a[1])\nprint(int(a[0]) + int(a[1]))", stdin: ["12 30"] },
  { name: "kesish va qo'shish", code: "a = [1, 2] + [3, 4]\nprint(a * 2, a[1:3])" },
  { name: "funksiya", code: "def eng_katta(a, b):\n    if a > b:\n        return a\n    return b\nprint(eng_katta(3, 9), eng_katta(-1, -5))" },
  { name: "funksiya ichma-ich", code: "def juftmi(n):\n    return n % 2 == 0\n\ndef nechta_juft(a):\n    n = 0\n    for x in a:\n        if juftmi(x):\n            n += 1\n    return n\n\nprint(nechta_juft([1, 2, 3, 4, 6]))" },
  { name: "return yo'q", code: "def salom(ism):\n    print('Salom,', ism)\nx = salom('Anvar')\nprint(x)" },
  { name: "rekursiya", code: "def fakt(n):\n    if n <= 1:\n        return 1\n    return n * fakt(n - 1)\nprint(fakt(10), fakt(20))" },
  { name: "lokal o'zgaruvchi", code: "x = 10\ndef f(x):\n    x = x + 1\n    return x\nprint(f(5), x)" },
  { name: "tub son", code: "def tubmi(n):\n    if n < 2:\n        return False\n    d = 2\n    while d * d <= n:\n        if n % d == 0:\n            return False\n        d += 1\n    return True\n\nfor n in range(1, 20):\n    if tubmi(n):\n        print(n)" },
  { name: "Fibonachchi", code: "a = 0\nb = 1\nfor i in range(15):\n    print(a)\n    a, b = b, a + b" },
  { name: "bool son sifatida", code: "print(True + True, False * 5, int(True))" },
  { name: "bo'sh ro'yxat va shart", code: "a = []\nif a:\n    print('bor')\nelse:\n    print('bo\\'sh')\nprint(len(a))" },
  { name: "list(map) bilan kirish", code: "a = list(map(int, input().split()))\nprint(a, sum(a), len(a), max(a))", stdin: ["3 1 4 1 5"] },
  { name: "map bilan ikki son", code: "a, b = map(int, input().split())\nprint(a + b, a * b)", stdin: ["12 30"] },
  { name: "map ustida yurish", code: "s = 0\nfor x in map(int, ['1', '2', '3']):\n    s += x\nprint(s, sum(map(int, '123')), max(map(len, ['a', 'bbb'])))" },
  { name: "map o'z funksiyasi bilan", code: "def kv(x):\n    return x * x\nprint(list(map(kv, [1, 2, 3])), sorted(map(abs, [-3, 1, -2])), list(map(str, [1, 2])))" },
  { name: "list()", code: "print(list('abc'), list(range(4)), list([1, 2]), list())\na = [1, 2]\nb = list(a)\nb.append(3)\nprint(a, b)" },
  { name: "print end va sep", code: "for i in range(3):\n    print(i, end=' ')\nprint()\nprint(1, 2, 3, sep='-')\nprint('a', 'b', sep='', end='!\\n')\nprint('x', end='')\nprint('y')" },
  { name: "ord va chr", code: "print(ord('a'), chr(98), chr(ord('a') + 2), ord('A') - ord('a'))" },
  { name: "join", code: "a = ['1', '2', '3']\nprint(' '.join(a), '-'.join('abc'), ''.join([]), ' '.join(map(str, [4, 5, 6])))" },
  { name: "in range", code: "print(5 in range(10), 10 in range(10), 4 in range(0, 10, 2), 7 in range(10, 0, -3), -1 in range(5))" },
  { name: "katta sikl", code: "s = 0\nfor i in range(100000):\n    s += i\nprint(s)" },
  { name: "oxirida Tab'li bo'sh satr", code: "x = 1\n\t\nprint(x)" },
];

// Xato bilan tugaydigan dasturlar: xato turi python3 dagi bilan bir xil bo'lishi kerak
const ERRORS = [
  { name: "nomsiz quti", code: "print(x)", type: "NameError" },
  { name: "nolga bo'lish", code: "print(1 / 0)", type: "ZeroDivisionError" },
  { name: "butun bo'lishda nol", code: "print(1 // 0)", type: "ZeroDivisionError" },
  { name: "matn + son", code: 'print("5" + 5)', type: "TypeError" },
  { name: "son + matn", code: 'print(5 + "5")', type: "TypeError" },
  { name: "int() xato", code: 'print(int("salom"))', type: "ValueError" },
  { name: "ro'yxatdan tashqari", code: "a = [1, 2]\nprint(a[5])", type: "IndexError" },
  { name: "satrdan tashqari", code: 's = "ab"\nprint(s[9])', type: "IndexError" },
  { name: "len(son)", code: "print(len(5))", type: "TypeError" },
  { name: "solishtirib bo'lmadi", code: 'print(1 < "a")', type: "TypeError" },
  { name: "qavs yopilmagan", code: 'print("salom"', type: "SyntaxError" },
  { name: "qo'shtirnoq yopilmagan", code: 'print("salom)', type: "SyntaxError" },
  { name: "ikki nuqta yo'q", code: "if 1 > 0\n    print(1)", type: "SyntaxError" },
  { name: "otstup yo'q", code: "if 1 > 0:\nprint(1)", type: "IndentationError" },
  { name: "keraksiz otstup", code: "x = 1\n    y = 2", type: "IndentationError" },
  { name: "funksiyaga kam qiymat", code: "def f(a, b):\n    return a\nprint(f(1))", type: "TypeError" },
  { name: "chaqirib bo'lmaydi", code: "x = 5\nprint(x(3))", type: "TypeError" },
  { name: "satrni o'zgartirish", code: 's = "ab"\ns[0] = "c"', type: "TypeError" },
  { name: "map indeksi", code: "m = map(int, ['1'])\nprint(m[0])", type: "TypeError" },
  { name: "len(map)", code: "print(len(map(int, ['1'])))", type: "TypeError" },
  { name: "join son bilan", code: "print(' '.join([1, 2]))", type: "TypeError" },
  { name: "ord uzun satr", code: "print(ord('ab'))", type: "TypeError" },
  { name: "sep son", code: "print(1, 2, sep=3)", type: "TypeError" },
  { name: "funksiya ichida break", code: "def f():\n    break\nfor i in range(3):\n    f()", type: "SyntaxError" },
];

module.exports = { PROGRAMS, ERRORS };
